Import ('user_options_dict')
Import ('library_env')

memutil_env = library_env.Copy ()

source_files = ['intern/MEM_RefCountedC-Api.cpp']

memutil_env.Append (CPPPATH = ['.'])

memutil_env.Library (target='#'+user_options_dict['BUILD_DIR']+'/lib/blender_MEM', source=source_files)
