#!/usr/bin/python
Import ('env')

objs = []

o = SConscript('intern/SConscript')
objs += o

incs = '#/intern/guardedalloc ../blenkernel ../blenlib ../makesdna intern .'

env.BlenderLib ( 'bf_rna', objs, Split(incs), [], libtype=['core','intern'], priority = [95, 95] )
