#!/usr/bin/python
Import ('env')

objs = []

o = SConscript('intern/SConscript')
objs += o

incs = '#/intern/guardedalloc ../blenkernel ../blenlib ../makesdna intern .'
incs += ' ../windowmanager ../editors/include ../imbuf ../ikplugin'
incs += ' ../render/extern/include'

defs = []

if env['WITH_BF_OPENEXR']:
	defs.append('WITH_OPENEXR')

if env['WITH_BF_OPENJPEG']:
	defs.append('WITH_OPENJPEG')

if env['WITH_BF_DDS']:
	defs.append('WITH_DDS')

if env['WITH_BF_FFMPEG']:
	defs.append('WITH_FFMPEG')
	incs += ' ' + env['BF_FFMPEG_INC']

if env['WITH_BF_OGG']:
	defs.append('WITH_OGG')

if env['WITH_BF_QUICKTIME']:
	defs.append('WITH_QUICKTIME')
	incs += ' ../quicktime'

if env['WITH_BF_LCMS']:
	defs.append('WITH_LCMS')

if env['WITH_BF_GAMEENGINE']:
	defs.append('GAMEBLENDER=1')

if env['BF_UNIT_TEST']:
	defs.append('UNIT_TEST')


if env['OURPLATFORM'] == 'linux2':
	cflags='-pthread'
    	incs += ' ../../../extern/binreloc/include'

if env['OURPLATFORM'] in ('win32-vc', 'win32-mingw', 'linuxcross', 'win64-vc'):
	incs += ' ' + env['BF_PTHREADS_INC']

env.BlenderLib ( 'bf_rna', objs, Split(incs), defines=defs, libtype=['core','player'], priority = [165,20] )
