Import ('user_options_dict')
Import ('library_env')

expressions_env = library_env.Copy ()

source_files = ['BoolValue.cpp',
                'ConstExpr.cpp',
                'EmptyValue.cpp',
                'ErrorValue.cpp',
                'EXP_C-Api.cpp',
                'Expression.cpp',
                'FloatValue.cpp',
                'IdentifierExpr.cpp',
                'IfExpr.cpp',
                'InputParser.cpp',
                'IntValue.cpp',
                'KX_HashedPtr.cpp',
                'ListValue.cpp',
                'Operator1Expr.cpp',
                'Operator2Expr.cpp',
                'PyObjectPlus.cpp',
                'StringValue.cpp',
                'Value.cpp',
                'VectorValue.cpp']

expressions_env.Append (CPPPATH = ['.',
                                   '#source/kernel/gen_system',
                                   '#intern/string'])

expressions_env.Append (CPPPATH = user_options_dict['PYTHON_INCLUDE'])

expressions_env.Library (target='#'+user_options_dict['BUILD_DIR']+'/lib/blender_expressions', source=source_files)
