import bpy


from mathutils import Color


def create(obj):
    # generated by rigify.utils.write_metarig
    bpy.ops.object.mode_set(mode='EDIT')
    arm = obj.data

    for i in range(6):
        arm.rigify_colors.add()

    arm.rigify_colors[0].name = "Root"
    arm.rigify_colors[0].active = Color((0.5490196347236633, 1.0, 1.0))
    arm.rigify_colors[0].normal = Color((0.4352940022945404, 0.18431399762630463, 0.4156860113143921))
    arm.rigify_colors[0].select = Color((0.31372547149658203, 0.7843138575553894, 1.0))
    arm.rigify_colors[0].standard_colors_lock = True
    arm.rigify_colors[1].name = "IK"
    arm.rigify_colors[1].active = Color((0.5490196347236633, 1.0, 1.0))
    arm.rigify_colors[1].normal = Color((0.6039220094680786, 0.0, 0.0))
    arm.rigify_colors[1].select = Color((0.31372547149658203, 0.7843138575553894, 1.0))
    arm.rigify_colors[1].standard_colors_lock = True
    arm.rigify_colors[2].name = "Special"
    arm.rigify_colors[2].active = Color((0.5490196347236633, 1.0, 1.0))
    arm.rigify_colors[2].normal = Color((0.9568629860877991, 0.7882350087165833, 0.04705899953842163))
    arm.rigify_colors[2].select = Color((0.31372547149658203, 0.7843138575553894, 1.0))
    arm.rigify_colors[2].standard_colors_lock = True
    arm.rigify_colors[3].name = "Tweak"
    arm.rigify_colors[3].active = Color((0.5490196347236633, 1.0, 1.0))
    arm.rigify_colors[3].normal = Color((0.03921600058674812, 0.21176500618457794, 0.5803920030593872))
    arm.rigify_colors[3].select = Color((0.31372547149658203, 0.7843138575553894, 1.0))
    arm.rigify_colors[3].standard_colors_lock = True
    arm.rigify_colors[4].name = "FK"
    arm.rigify_colors[4].active = Color((0.5490196347236633, 1.0, 1.0))
    arm.rigify_colors[4].normal = Color((0.11764699965715408, 0.5686269998550415, 0.035294000059366226))
    arm.rigify_colors[4].select = Color((0.31372547149658203, 0.7843138575553894, 1.0))
    arm.rigify_colors[4].standard_colors_lock = True
    arm.rigify_colors[5].name = "Extra"
    arm.rigify_colors[5].active = Color((0.5490196347236633, 1.0, 1.0))
    arm.rigify_colors[5].normal = Color((0.9686279892921448, 0.2509799897670746, 0.09411799907684326))
    arm.rigify_colors[5].select = Color((0.31372547149658203, 0.7843138575553894, 1.0))
    arm.rigify_colors[5].standard_colors_lock = True

    for i in range(29):
        arm.rigify_layers.add()

    arm.rigify_layers[0].name = "Face"
    arm.rigify_layers[0].row = 1
    arm.rigify_layers[0].set = False
    arm.rigify_layers[0].group = 6
    arm.rigify_layers[1].name = "Face (Tweak)"
    arm.rigify_layers[1].row = 2
    arm.rigify_layers[1].set = False
    arm.rigify_layers[1].group = 4
    arm.rigify_layers[2].name = " "
    arm.rigify_layers[2].row = 1
    arm.rigify_layers[2].set = False
    arm.rigify_layers[2].group = 0
    arm.rigify_layers[3].name = "Spine"
    arm.rigify_layers[3].row = 3
    arm.rigify_layers[3].set = False
    arm.rigify_layers[3].group = 3
    arm.rigify_layers[4].name = "Spine (Tweak)"
    arm.rigify_layers[4].row = 4
    arm.rigify_layers[4].set = False
    arm.rigify_layers[4].group = 4
    arm.rigify_layers[5].name = " "
    arm.rigify_layers[5].row = 1
    arm.rigify_layers[5].set = False
    arm.rigify_layers[5].group = 0
    arm.rigify_layers[6].name = " "
    arm.rigify_layers[6].row = 1
    arm.rigify_layers[6].set = False
    arm.rigify_layers[6].group = 0
    arm.rigify_layers[7].name = "Wing.L"
    arm.rigify_layers[7].row = 6
    arm.rigify_layers[7].set = False
    arm.rigify_layers[7].group = 5
    arm.rigify_layers[8].name = ""
    arm.rigify_layers[8].row = 8
    arm.rigify_layers[8].set = False
    arm.rigify_layers[8].group = 0
    arm.rigify_layers[9].name = "Wing.L (Tweak)"
    arm.rigify_layers[9].row = 7
    arm.rigify_layers[9].set = False
    arm.rigify_layers[9].group = 4
    arm.rigify_layers[10].name = "Wing.R"
    arm.rigify_layers[10].row = 6
    arm.rigify_layers[10].set = False
    arm.rigify_layers[10].group = 5
    arm.rigify_layers[11].name = ""
    arm.rigify_layers[11].row = 8
    arm.rigify_layers[11].set = False
    arm.rigify_layers[11].group = 0
    arm.rigify_layers[12].name = "Wing.R (Tweak)"
    arm.rigify_layers[12].row = 7
    arm.rigify_layers[12].set = False
    arm.rigify_layers[12].group = 4
    arm.rigify_layers[13].name = "Leg.L (IK)"
    arm.rigify_layers[13].row = 10
    arm.rigify_layers[13].set = False
    arm.rigify_layers[13].group = 2
    arm.rigify_layers[14].name = "Leg.L (FK)"
    arm.rigify_layers[14].row = 11
    arm.rigify_layers[14].set = False
    arm.rigify_layers[14].group = 5
    arm.rigify_layers[15].name = "Leg.L (Tweak)"
    arm.rigify_layers[15].row = 12
    arm.rigify_layers[15].set = False
    arm.rigify_layers[15].group = 4
    arm.rigify_layers[16].name = " Leg.R (IK)"
    arm.rigify_layers[16].row = 10
    arm.rigify_layers[16].set = False
    arm.rigify_layers[16].group = 2
    arm.rigify_layers[17].name = " Leg.R (FK)"
    arm.rigify_layers[17].row = 11
    arm.rigify_layers[17].set = False
    arm.rigify_layers[17].group = 5
    arm.rigify_layers[18].name = " Leg.R (Tweak)"
    arm.rigify_layers[18].row = 12
    arm.rigify_layers[18].set = False
    arm.rigify_layers[18].group = 4
    arm.rigify_layers[19].name = " "
    arm.rigify_layers[19].row = 1
    arm.rigify_layers[19].set = False
    arm.rigify_layers[19].group = 0
    arm.rigify_layers[20].name = " "
    arm.rigify_layers[20].row = 1
    arm.rigify_layers[20].set = False
    arm.rigify_layers[20].group = 0
    arm.rigify_layers[21].name = "Claws"
    arm.rigify_layers[21].row = 13
    arm.rigify_layers[21].set = False
    arm.rigify_layers[21].group = 6
    arm.rigify_layers[22].name = "Claws (Tweak)"
    arm.rigify_layers[22].row = 14
    arm.rigify_layers[22].set = False
    arm.rigify_layers[22].group = 4
    arm.rigify_layers[23].name = " "
    arm.rigify_layers[23].row = 1
    arm.rigify_layers[23].set = False
    arm.rigify_layers[23].group = 0
    arm.rigify_layers[24].name = "Feathers"
    arm.rigify_layers[24].row = 8
    arm.rigify_layers[24].set = False
    arm.rigify_layers[24].group = 6
    arm.rigify_layers[25].name = " "
    arm.rigify_layers[25].row = 1
    arm.rigify_layers[25].set = False
    arm.rigify_layers[25].group = 0
    arm.rigify_layers[26].name = " "
    arm.rigify_layers[26].row = 1
    arm.rigify_layers[26].set = False
    arm.rigify_layers[26].group = 0
    arm.rigify_layers[27].name = " "
    arm.rigify_layers[27].row = 1
    arm.rigify_layers[27].set = False
    arm.rigify_layers[27].group = 0
    arm.rigify_layers[28].name = "Root"
    arm.rigify_layers[28].row = 14
    arm.rigify_layers[28].set = False
    arm.rigify_layers[28].group = 1

    bones = {}

    bone = arm.edit_bones.new('spine')
    bone.head[:] = -0.0000, 0.1371, 0.0894
    bone.tail[:] = -0.0000, 0.1039, 0.0907
    bone.roll = 0.0000
    bone.use_connect = False
    bones['spine'] = bone.name
    bone = arm.edit_bones.new('spine.001')
    bone.head[:] = -0.0000, 0.1039, 0.0907
    bone.tail[:] = -0.0000, 0.0757, 0.0880
    bone.roll = 0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['spine']]
    bones['spine.001'] = bone.name
    bone = arm.edit_bones.new('t_feather.L')
    bone.head[:] = 0.0112, 0.1017, 0.0907
    bone.tail[:] = 0.0167, 0.1345, 0.0894
    bone.roll = 0.0032
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['spine']]
    bones['t_feather.L'] = bone.name
    bone = arm.edit_bones.new('t_feather.R')
    bone.head[:] = -0.0112, 0.1017, 0.0907
    bone.tail[:] = -0.0167, 0.1345, 0.0894
    bone.roll = -0.0032
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['spine']]
    bones['t_feather.R'] = bone.name
    bone = arm.edit_bones.new('spine.002')
    bone.head[:] = -0.0000, 0.0757, 0.0880
    bone.tail[:] = -0.0000, 0.0451, 0.0845
    bone.roll = 0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['spine.001']]
    bones['spine.002'] = bone.name
    bone = arm.edit_bones.new('spine.003')
    bone.head[:] = -0.0000, 0.0451, 0.0845
    bone.tail[:] = -0.0000, 0.0192, 0.0888
    bone.roll = 0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['spine.002']]
    bones['spine.003'] = bone.name
    bone = arm.edit_bones.new('spine.004')
    bone.head[:] = -0.0000, 0.0192, 0.0888
    bone.tail[:] = -0.0000, -0.0106, 0.0979
    bone.roll = 0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['spine.003']]
    bones['spine.004'] = bone.name
    bone = arm.edit_bones.new('spine.005')
    bone.head[:] = -0.0000, -0.0106, 0.0979
    bone.tail[:] = -0.0000, -0.0298, 0.1158
    bone.roll = 0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['spine.004']]
    bones['spine.005'] = bone.name
    bone = arm.edit_bones.new('pelvis.L')
    bone.head[:] = -0.0000, 0.0192, 0.0888
    bone.tail[:] = 0.0250, 0.0070, 0.0782
    bone.roll = -0.0369
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['spine.004']]
    bones['pelvis.L'] = bone.name
    bone = arm.edit_bones.new('pelvis.R')
    bone.head[:] = 0.0000, 0.0192, 0.0888
    bone.tail[:] = -0.0250, 0.0070, 0.0782
    bone.roll = 0.0369
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['spine.004']]
    bones['pelvis.R'] = bone.name
    bone = arm.edit_bones.new('thigh.L')
    bone.head[:] = 0.0149, 0.0063, 0.0739
    bone.tail[:] = 0.0149, 0.0143, 0.0391
    bone.roll = 0.0000
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['spine.004']]
    bones['thigh.L'] = bone.name
    bone = arm.edit_bones.new('thigh.R')
    bone.head[:] = -0.0149, 0.0063, 0.0739
    bone.tail[:] = -0.0149, 0.0143, 0.0391
    bone.roll = -0.0000
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['spine.004']]
    bones['thigh.R'] = bone.name
    bone = arm.edit_bones.new('shoulder.L')
    bone.head[:] = 0.0014, -0.0217, 0.0893
    bone.tail[:] = 0.0076, -0.0020, 0.1179
    bone.roll = 1.3977
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['spine.005']]
    bones['shoulder.L'] = bone.name
    bone = arm.edit_bones.new('spine.006')
    bone.head[:] = -0.0000, -0.0298, 0.1158
    bone.tail[:] = -0.0000, -0.0417, 0.1348
    bone.roll = 0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['spine.005']]
    bones['spine.006'] = bone.name
    bone = arm.edit_bones.new('shoulder.R')
    bone.head[:] = -0.0014, -0.0217, 0.0893
    bone.tail[:] = -0.0076, -0.0020, 0.1179
    bone.roll = -1.3977
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['spine.005']]
    bones['shoulder.R'] = bone.name
    bone = arm.edit_bones.new('shin.L')
    bone.head[:] = 0.0149, 0.0143, 0.0391
    bone.tail[:] = 0.0149, 0.0015, 0.0074
    bone.roll = 0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['thigh.L']]
    bones['shin.L'] = bone.name
    bone = arm.edit_bones.new('shin.R')
    bone.head[:] = -0.0149, 0.0143, 0.0391
    bone.tail[:] = -0.0149, 0.0015, 0.0074
    bone.roll = -0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['thigh.R']]
    bones['shin.R'] = bone.name
    bone = arm.edit_bones.new('Wing.L')
    bone.head[:] = 0.0089, 0.0141, 0.1157
    bone.tail[:] = 0.0485, 0.0107, 0.1163
    bone.roll = 2.8221
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['shoulder.L']]
    bones['Wing.L'] = bone.name
    bone = arm.edit_bones.new('neck.001')
    bone.head[:] = -0.0000, -0.0417, 0.1348
    bone.tail[:] = -0.0000, -0.0458, 0.1429
    bone.roll = 0.0001
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['spine.006']]
    bones['neck.001'] = bone.name
    bone = arm.edit_bones.new('Wing.R')
    bone.head[:] = -0.0089, 0.0141, 0.1157
    bone.tail[:] = -0.0485, 0.0107, 0.1163
    bone.roll = -2.8221
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['shoulder.R']]
    bones['Wing.R'] = bone.name
    bone = arm.edit_bones.new('foot.L')
    bone.head[:] = 0.0149, 0.0015, 0.0074
    bone.tail[:] = 0.0149, -0.0033, 0.0045
    bone.roll = 0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['shin.L']]
    bones['foot.L'] = bone.name
    bone = arm.edit_bones.new('foot.R')
    bone.head[:] = -0.0149, 0.0015, 0.0074
    bone.tail[:] = -0.0149, -0.0033, 0.0045
    bone.roll = -0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['shin.R']]
    bones['foot.R'] = bone.name
    bone = arm.edit_bones.new('Wing.001.L')
    bone.head[:] = 0.0485, 0.0107, 0.1163
    bone.tail[:] = 0.0919, 0.0021, 0.1191
    bone.roll = 2.7596
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Wing.L']]
    bones['Wing.001.L'] = bone.name
    bone = arm.edit_bones.new('w_feather.004.L')
    bone.head[:] = 0.0382, 0.0253, 0.1081
    bone.tail[:] = 0.0553, 0.0878, 0.0901
    bone.roll = 3.0872
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Wing.L']]
    bones['w_feather.004.L'] = bone.name
    bone = arm.edit_bones.new('neck.002')
    bone.head[:] = -0.0000, -0.0458, 0.1429
    bone.tail[:] = -0.0000, -0.0483, 0.1498
    bone.roll = 0.0001
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['neck.001']]
    bones['neck.002'] = bone.name
    bone = arm.edit_bones.new('Wing.001.R')
    bone.head[:] = -0.0485, 0.0107, 0.1163
    bone.tail[:] = -0.0919, 0.0021, 0.1191
    bone.roll = -2.7596
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Wing.R']]
    bones['Wing.001.R'] = bone.name
    bone = arm.edit_bones.new('w_feather.004.R')
    bone.head[:] = -0.0382, 0.0253, 0.1081
    bone.tail[:] = -0.0553, 0.0878, 0.0901
    bone.roll = -3.0872
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Wing.R']]
    bones['w_feather.004.R'] = bone.name
    bone = arm.edit_bones.new('toe.L')
    bone.head[:] = 0.0149, -0.0033, 0.0045
    bone.tail[:] = 0.0149, -0.0404, 0.0006
    bone.roll = 3.1416
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['foot.L']]
    bones['toe.L'] = bone.name
    bone = arm.edit_bones.new('toe.R')
    bone.head[:] = -0.0149, -0.0033, 0.0045
    bone.tail[:] = -0.0149, -0.0404, 0.0006
    bone.roll = -3.1416
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['foot.R']]
    bones['toe.R'] = bone.name
    bone = arm.edit_bones.new('Wing.002.L')
    bone.head[:] = 0.0919, 0.0021, 0.1191
    bone.tail[:] = 0.2128, 0.0178, 0.1159
    bone.roll = 2.8565
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Wing.001.L']]
    bones['Wing.002.L'] = bone.name
    bone = arm.edit_bones.new('w_feather.003.L')
    bone.head[:] = 0.0754, 0.0212, 0.1122
    bone.tail[:] = 0.1342, 0.0830, 0.0901
    bone.roll = 3.0993
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Wing.001.L']]
    bones['w_feather.003.L'] = bone.name
    bone = arm.edit_bones.new('head')
    bone.head[:] = -0.0000, -0.0483, 0.1498
    bone.tail[:] = -0.0000, -0.1026, 0.1815
    bone.roll = 0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['neck.002']]
    bones['head'] = bone.name
    bone = arm.edit_bones.new('Wing.002.R')
    bone.head[:] = -0.0919, 0.0021, 0.1191
    bone.tail[:] = -0.2128, 0.0178, 0.1159
    bone.roll = -2.8565
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Wing.001.R']]
    bones['Wing.002.R'] = bone.name
    bone = arm.edit_bones.new('w_feather.003.R')
    bone.head[:] = -0.0754, 0.0212, 0.1122
    bone.tail[:] = -0.1342, 0.0830, 0.0901
    bone.roll = -3.0993
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Wing.001.R']]
    bones['w_feather.003.R'] = bone.name
    bone = arm.edit_bones.new('toes_parent.L')
    bone.head[:] = 0.0149, -0.0033, 0.0045
    bone.tail[:] = 0.0149, -0.0096, 0.0037
    bone.roll = 3.1416
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['toe.L']]
    bones['toes_parent.L'] = bone.name
    bone = arm.edit_bones.new('t_thumb.001.L')
    bone.head[:] = 0.0136, 0.0051, 0.0022
    bone.tail[:] = 0.0131, 0.0142, 0.0026
    bone.roll = 3.1406
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['toe.L']]
    bones['t_thumb.001.L'] = bone.name
    bone = arm.edit_bones.new('toes_parent.R')
    bone.head[:] = -0.0149, -0.0033, 0.0045
    bone.tail[:] = -0.0149, -0.0096, 0.0037
    bone.roll = -3.1416
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['toe.R']]
    bones['toes_parent.R'] = bone.name
    bone = arm.edit_bones.new('t_thumb.001.R')
    bone.head[:] = -0.0136, 0.0051, 0.0022
    bone.tail[:] = -0.0131, 0.0142, 0.0026
    bone.roll = -3.1406
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['toe.R']]
    bones['t_thumb.001.R'] = bone.name
    bone = arm.edit_bones.new('w_feather.001.L')
    bone.head[:] = 0.1595, -0.0062, 0.1163
    bone.tail[:] = 0.2489, -0.0055, 0.1224
    bone.roll = 2.9290
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Wing.002.L']]
    bones['w_feather.001.L'] = bone.name
    bone = arm.edit_bones.new('w_feather.002.L')
    bone.head[:] = 0.1218, 0.0331, 0.1099
    bone.tail[:] = 0.1812, 0.0495, 0.1068
    bone.roll = 2.8770
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Wing.002.L']]
    bones['w_feather.002.L'] = bone.name
    bone = arm.edit_bones.new('beak.001.T')
    bone.head[:] = -0.0000, -0.0703, 0.1580
    bone.tail[:] = -0.0000, -0.0927, 0.1597
    bone.roll = 0.0001
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['head']]
    bones['beak.001.T'] = bone.name
    bone = arm.edit_bones.new('beak_001.B')
    bone.head[:] = -0.0000, -0.0703, 0.1556
    bone.tail[:] = -0.0000, -0.0914, 0.1555
    bone.roll = 0.0001
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['head']]
    bones['beak_001.B'] = bone.name
    bone = arm.edit_bones.new('eye.L')
    bone.head[:] = 0.0055, -0.0647, 0.1615
    bone.tail[:] = 0.0198, -0.0675, 0.1615
    bone.roll = 0.0000
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['head']]
    bones['eye.L'] = bone.name
    bone = arm.edit_bones.new('eye.R')
    bone.head[:] = -0.0055, -0.0647, 0.1615
    bone.tail[:] = -0.0198, -0.0675, 0.1615
    bone.roll = -0.0000
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['head']]
    bones['eye.R'] = bone.name
    bone = arm.edit_bones.new('n_feather.001.L')
    bone.head[:] = 0.0098, -0.0390, 0.1566
    bone.tail[:] = 0.0131, -0.0247, 0.1430
    bone.roll = -0.0380
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['head']]
    bones['n_feather.001.L'] = bone.name
    bone = arm.edit_bones.new('n_feather.001.R')
    bone.head[:] = -0.0098, -0.0390, 0.1566
    bone.tail[:] = -0.0131, -0.0247, 0.1430
    bone.roll = 0.0380
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['head']]
    bones['n_feather.001.R'] = bone.name
    bone = arm.edit_bones.new('skull.006.L')
    bone.head[:] = 0.0033, -0.0587, 0.1538
    bone.tail[:] = 0.0162, -0.0666, 0.1509
    bone.roll = 1.6532
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['head']]
    bones['skull.006.L'] = bone.name
    bone = arm.edit_bones.new('skull.006.R')
    bone.head[:] = -0.0033, -0.0587, 0.1538
    bone.tail[:] = -0.0162, -0.0666, 0.1509
    bone.roll = -1.6532
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['head']]
    bones['skull.006.R'] = bone.name
    bone = arm.edit_bones.new('w_feather.001.R')
    bone.head[:] = -0.1595, -0.0062, 0.1163
    bone.tail[:] = -0.2489, -0.0055, 0.1224
    bone.roll = -2.9290
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Wing.002.R']]
    bones['w_feather.001.R'] = bone.name
    bone = arm.edit_bones.new('w_feather.002.R')
    bone.head[:] = -0.1218, 0.0331, 0.1099
    bone.tail[:] = -0.1812, 0.0495, 0.1068
    bone.roll = -2.8770
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Wing.002.R']]
    bones['w_feather.002.R'] = bone.name
    bone = arm.edit_bones.new('t_ring.001.L')
    bone.head[:] = 0.0183, -0.0026, 0.0034
    bone.tail[:] = 0.0216, -0.0129, 0.0038
    bone.roll = 6.0340
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['toes_parent.L']]
    bones['t_ring.001.L'] = bone.name
    bone = arm.edit_bones.new('t_index.001.L')
    bone.head[:] = 0.0122, -0.0026, 0.0034
    bone.tail[:] = 0.0093, -0.0130, 0.0038
    bone.roll = 6.5631
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['toes_parent.L']]
    bones['t_index.001.L'] = bone.name
    bone = arm.edit_bones.new('t_middle.001.L')
    bone.head[:] = 0.0149, -0.0050, 0.0034
    bone.tail[:] = 0.0149, -0.0207, 0.0040
    bone.roll = 3.1416
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['toes_parent.L']]
    bones['t_middle.001.L'] = bone.name
    bone = arm.edit_bones.new('t_thumb.002.L')
    bone.head[:] = 0.0131, 0.0142, 0.0026
    bone.tail[:] = 0.0126, 0.0241, 0.0003
    bone.roll = 3.1472
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['t_thumb.001.L']]
    bones['t_thumb.002.L'] = bone.name
    bone = arm.edit_bones.new('t_ring.001.R')
    bone.head[:] = -0.0183, -0.0026, 0.0034
    bone.tail[:] = -0.0216, -0.0129, 0.0038
    bone.roll = -6.0340
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['toes_parent.R']]
    bones['t_ring.001.R'] = bone.name
    bone = arm.edit_bones.new('t_index.001.R')
    bone.head[:] = -0.0122, -0.0026, 0.0034
    bone.tail[:] = -0.0093, -0.0130, 0.0038
    bone.roll = -6.5631
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['toes_parent.R']]
    bones['t_index.001.R'] = bone.name
    bone = arm.edit_bones.new('t_middle.001.R')
    bone.head[:] = -0.0149, -0.0050, 0.0034
    bone.tail[:] = -0.0149, -0.0207, 0.0040
    bone.roll = -3.1416
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['toes_parent.R']]
    bones['t_middle.001.R'] = bone.name
    bone = arm.edit_bones.new('t_thumb.002.R')
    bone.head[:] = -0.0131, 0.0142, 0.0026
    bone.tail[:] = -0.0126, 0.0241, 0.0003
    bone.roll = -3.1472
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['t_thumb.001.R']]
    bones['t_thumb.002.R'] = bone.name
    bone = arm.edit_bones.new('beak.002.T')
    bone.head[:] = -0.0000, -0.0927, 0.1597
    bone.tail[:] = -0.0000, -0.1131, 0.1533
    bone.roll = 0.0001
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['beak.001.T']]
    bones['beak.002.T'] = bone.name
    bone = arm.edit_bones.new('beak.002.B')
    bone.head[:] = -0.0000, -0.0914, 0.1555
    bone.tail[:] = -0.0000, -0.1084, 0.1519
    bone.roll = 0.0001
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['beak_001.B']]
    bones['beak.002.B'] = bone.name
    bone = arm.edit_bones.new('tongue.001.L')
    bone.head[:] = -0.0000, -0.0792, 0.1536
    bone.tail[:] = -0.0000, -0.0840, 0.1555
    bone.roll = 0.0001
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['beak_001.B']]
    bones['tongue.001.L'] = bone.name
    bone = arm.edit_bones.new('t_ring.002.L')
    bone.head[:] = 0.0216, -0.0129, 0.0038
    bone.tail[:] = 0.0237, -0.0195, 0.0032
    bone.roll = 0.5806
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['t_ring.001.L']]
    bones['t_ring.002.L'] = bone.name
    bone = arm.edit_bones.new('t_index.002.L')
    bone.head[:] = 0.0093, -0.0130, 0.0038
    bone.tail[:] = 0.0067, -0.0223, 0.0032
    bone.roll = -0.4957
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['t_index.001.L']]
    bones['t_index.002.L'] = bone.name
    bone = arm.edit_bones.new('t_middle.002.L')
    bone.head[:] = 0.0149, -0.0207, 0.0040
    bone.tail[:] = 0.0149, -0.0308, 0.0031
    bone.roll = 3.1416
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['t_middle.001.L']]
    bones['t_middle.002.L'] = bone.name
    bone = arm.edit_bones.new('t_ring.002.R')
    bone.head[:] = -0.0216, -0.0129, 0.0038
    bone.tail[:] = -0.0237, -0.0195, 0.0032
    bone.roll = -0.5806
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['t_ring.001.R']]
    bones['t_ring.002.R'] = bone.name
    bone = arm.edit_bones.new('t_index.002.R')
    bone.head[:] = -0.0093, -0.0130, 0.0038
    bone.tail[:] = -0.0067, -0.0223, 0.0032
    bone.roll = 0.4957
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['t_index.001.R']]
    bones['t_index.002.R'] = bone.name
    bone = arm.edit_bones.new('t_middle.002.R')
    bone.head[:] = -0.0149, -0.0207, 0.0040
    bone.tail[:] = -0.0149, -0.0308, 0.0031
    bone.roll = -3.1416
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['t_middle.001.R']]
    bones['t_middle.002.R'] = bone.name
    bone = arm.edit_bones.new('tongue.002.L')
    bone.head[:] = -0.0000, -0.0840, 0.1555
    bone.tail[:] = -0.0000, -0.0874, 0.1553
    bone.roll = 0.0001
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['tongue.001.L']]
    bones['tongue.002.L'] = bone.name
    bone = arm.edit_bones.new('t_ring.003.L')
    bone.head[:] = 0.0237, -0.0195, 0.0032
    bone.tail[:] = 0.0261, -0.0270, 0.0009
    bone.roll = 1.5954
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['t_ring.002.L']]
    bones['t_ring.003.L'] = bone.name
    bone = arm.edit_bones.new('t_index.003.L')
    bone.head[:] = 0.0067, -0.0223, 0.0032
    bone.tail[:] = 0.0038, -0.0327, 0.0009
    bone.roll = 4.8853
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['t_index.002.L']]
    bones['t_index.003.L'] = bone.name
    bone = arm.edit_bones.new('t_middle.003.L')
    bone.head[:] = 0.0149, -0.0308, 0.0031
    bone.tail[:] = 0.0149, -0.0421, -0.0003
    bone.roll = 3.1416
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['t_middle.002.L']]
    bones['t_middle.003.L'] = bone.name
    bone = arm.edit_bones.new('t_ring.003.R')
    bone.head[:] = -0.0237, -0.0195, 0.0032
    bone.tail[:] = -0.0261, -0.0270, 0.0009
    bone.roll = -1.5954
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['t_ring.002.R']]
    bones['t_ring.003.R'] = bone.name
    bone = arm.edit_bones.new('t_index.003.R')
    bone.head[:] = -0.0067, -0.0223, 0.0032
    bone.tail[:] = -0.0038, -0.0327, 0.0009
    bone.roll = -4.8853
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['t_index.002.R']]
    bones['t_index.003.R'] = bone.name
    bone = arm.edit_bones.new('t_middle.003.R')
    bone.head[:] = -0.0149, -0.0308, 0.0031
    bone.tail[:] = -0.0149, -0.0421, -0.0003
    bone.roll = -3.1416
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['t_middle.002.R']]
    bones['t_middle.003.R'] = bone.name
    bone = arm.edit_bones.new('tongue.003.L')
    bone.head[:] = -0.0000, -0.0874, 0.1553
    bone.tail[:] = -0.0000, -0.0898, 0.1553
    bone.roll = 3.1416
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['tongue.002.L']]
    bones['tongue.003.L'] = bone.name

    bpy.ops.object.mode_set(mode='OBJECT')
    pbone = obj.pose.bones[bones['spine']]
    pbone.rigify_type = 'spines.super_spine'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    try:
        pbone.rigify_parameters.use_tail = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.tail_pos = 3
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.pivot_pos = 4
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.neck_pos = 8
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.copy_rotation_axes = [True, False, True]
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.tweak_layers = [False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['spine.001']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['t_feather.L']]
    pbone.rigify_type = 'basic.super_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False]
    try:
        pbone.rigify_parameters.make_widget = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['t_feather.R']]
    pbone.rigify_type = 'basic.super_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False]
    try:
        pbone.rigify_parameters.make_widget = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['spine.002']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['spine.003']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['spine.004']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['spine.005']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['pelvis.L']]
    pbone.rigify_type = 'basic.super_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    try:
        pbone.rigify_parameters.make_widget = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_control = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['pelvis.R']]
    pbone.rigify_type = 'basic.super_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    try:
        pbone.rigify_parameters.make_control = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_widget = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['thigh.L']]
    pbone.rigify_type = 'limbs.super_limb'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    try:
        pbone.rigify_parameters.limb_type = "paw"
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.tweak_layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.fk_layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['thigh.R']]
    pbone.rigify_type = 'limbs.super_limb'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    try:
        pbone.rigify_parameters.limb_type = "paw"
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.tweak_layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False]
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.fk_layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['shoulder.L']]
    pbone.rigify_type = 'basic.super_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    try:
        pbone.rigify_parameters.make_widget = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['spine.006']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['shoulder.R']]
    pbone.rigify_type = 'basic.super_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    try:
        pbone.rigify_parameters.make_widget = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['shin.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['shin.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['Wing.L']]
    pbone.rigify_type = 'limbs.simple_tentacle'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.rigify_parameters.copy_rotation_axes = [False, False, False]
    pbone.bone.layers = [False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    try:
        pbone.rigify_parameters.tweak_layers = [False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['neck.001']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['Wing.R']]
    pbone.rigify_type = 'limbs.simple_tentacle'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.rigify_parameters.copy_rotation_axes = [False, False, False]
    pbone.bone.layers = [False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    try:
        pbone.rigify_parameters.tweak_layers = [False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['foot.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['foot.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['Wing.001.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['w_feather.004.L']]
    pbone.rigify_type = 'basic.super_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False]
    try:
        pbone.rigify_parameters.make_widget = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['neck.002']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['Wing.001.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['w_feather.004.R']]
    pbone.rigify_type = 'basic.super_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False]
    try:
        pbone.rigify_parameters.make_widget = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['toe.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['toe.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['Wing.002.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['w_feather.003.L']]
    pbone.rigify_type = 'basic.super_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False]
    try:
        pbone.rigify_parameters.make_widget = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['head']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['Wing.002.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['w_feather.003.R']]
    pbone.rigify_type = 'basic.super_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False]
    try:
        pbone.rigify_parameters.make_widget = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['toes_parent.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['t_thumb.001.L']]
    pbone.rigify_type = 'limbs.simple_tentacle'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False]
    try:
        pbone.rigify_parameters.tweak_layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False]
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['toes_parent.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['t_thumb.001.R']]
    pbone.rigify_type = 'limbs.simple_tentacle'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False]
    try:
        pbone.rigify_parameters.tweak_layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False]
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['w_feather.001.L']]
    pbone.rigify_type = 'basic.super_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False]
    try:
        pbone.rigify_parameters.make_widget = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['w_feather.002.L']]
    pbone.rigify_type = 'basic.super_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False]
    try:
        pbone.rigify_parameters.make_widget = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['beak.001.T']]
    pbone.rigify_type = 'limbs.simple_tentacle'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['beak_001.B']]
    pbone.rigify_type = 'limbs.simple_tentacle'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['eye.L']]
    pbone.rigify_type = 'basic.super_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    try:
        pbone.rigify_parameters.make_widget = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['eye.R']]
    pbone.rigify_type = 'basic.super_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    try:
        pbone.rigify_parameters.make_widget = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['n_feather.001.L']]
    pbone.rigify_type = 'basic.super_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False]
    try:
        pbone.rigify_parameters.make_widget = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['n_feather.001.R']]
    pbone.rigify_type = 'basic.super_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False]
    try:
        pbone.rigify_parameters.make_widget = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['skull.006.L']]
    pbone.rigify_type = 'basic.super_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    try:
        pbone.rigify_parameters.make_widget = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_control = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['skull.006.R']]
    pbone.rigify_type = 'basic.super_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    try:
        pbone.rigify_parameters.make_widget = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_control = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['w_feather.001.R']]
    pbone.rigify_type = 'basic.super_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False]
    try:
        pbone.rigify_parameters.make_widget = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['w_feather.002.R']]
    pbone.rigify_type = 'basic.super_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False]
    try:
        pbone.rigify_parameters.make_widget = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['t_ring.001.L']]
    pbone.rigify_type = 'limbs.simple_tentacle'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False]
    try:
        pbone.rigify_parameters.tweak_layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False]
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['t_index.001.L']]
    pbone.rigify_type = 'limbs.simple_tentacle'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False]
    try:
        pbone.rigify_parameters.tweak_layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False]
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['t_middle.001.L']]
    pbone.rigify_type = 'limbs.simple_tentacle'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False]
    try:
        pbone.rigify_parameters.tweak_layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False]
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['t_thumb.002.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['t_ring.001.R']]
    pbone.rigify_type = 'limbs.simple_tentacle'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False]
    try:
        pbone.rigify_parameters.tweak_layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False]
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['t_index.001.R']]
    pbone.rigify_type = 'limbs.simple_tentacle'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False]
    try:
        pbone.rigify_parameters.tweak_layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False]
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['t_middle.001.R']]
    pbone.rigify_type = 'limbs.simple_tentacle'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False]
    try:
        pbone.rigify_parameters.tweak_layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False]
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['t_thumb.002.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['beak.002.T']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['beak.002.B']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['tongue.001.L']]
    pbone.rigify_type = 'limbs.simple_tentacle'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['t_ring.002.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['t_index.002.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['t_middle.002.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['t_ring.002.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['t_index.002.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['t_middle.002.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['tongue.002.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['t_ring.003.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['t_index.003.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['t_middle.003.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['t_ring.003.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['t_index.003.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['t_middle.003.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['tongue.003.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]

    bpy.ops.object.mode_set(mode='EDIT')
    for bone in arm.edit_bones:
        bone.select = False
        bone.select_head = False
        bone.select_tail = False
    for b in bones:
        bone = arm.edit_bones[bones[b]]
        bone.select = True
        bone.select_head = True
        bone.select_tail = True
        arm.edit_bones.active = bone

    arm.layers = [(x in [0, 3, 7, 10, 13, 16, 21, 24]) for x in range(32)]

if __name__ == "__main__":
    create(bpy.context.active_object)