#!/usr/bin/python
Import ('user_options_dict')
Import ('library_env')

blenplugin_env = library_env.Copy ()

source_files = ['intern/pluginapi.c']

blenplugin_env.Append (CPPPATH = ['.',
                                  '..',
                                  '#/intern/guardedalloc',
                                  '../blenlib',
                                  '../imbuf',
                                  '../makesdna'])

blenplugin_env.Library (target='#'+user_options_dict['BUILD_DIR']+'/lib/blender_blenpluginapi', source=source_files)
