#!/usr/bin/python
Import ('env')

sources = env.Glob('intern/*.c')

incs = '. .. #/intern/guardedalloc ../blenlib ../imbuf ../makesdna'

defs = []

if env['WITH_BF_QUICKTIME']:
	defs.append('WITH_QUICKTIME')
	incs += ' ' + env['BF_QUICKTIME_INC']

env.BlenderLib ( libname = 'bf_blenpluginapi', sources = sources, includes = Split(incs), defines = defs, libtype=['core'], priority = [170] )
