avi_env = Environment()

# Import the C flags set in the SConstruct file
Import ('cflags')
Import ('cxxflags')
Import ('defines')
Import ('extra_includes')
avi_env.Append (CCFLAGS = cflags)
avi_env.Append (CXXFLAGS = cxxflags)
avi_env.Append (CPPDEFINES = defines)

source_files = ['intern/avi.c',
                'intern/avirgb.c',
                'intern/codecs.c',
                'intern/endian.c',
                'intern/mjpeg.c',
                'intern/options.c',
                'intern/rgb32.c']

avi_env.Append (CPPPATH = ['.',
                           '#/intern/guardedalloc'])

avi_env.Append (CPPPATH=extra_includes)
avi_env.Library (target='#/lib/blender_avi', source=source_files)
