#!/usr/bin/python
Import ('extra_includes')
Import ('user_options_dict')
Import ('library_env')

avi_env = library_env.Copy ()

source_files = ['intern/avi.c',
                'intern/avirgb.c',
                'intern/codecs.c',
                'intern/endian.c',
                'intern/mjpeg.c',
                'intern/options.c',
                'intern/rgb32.c']

avi_env.Append (CPPPATH = ['.',
                           '#/intern/guardedalloc'])

avi_env.Append (CPPPATH=user_options_dict['JPEG_INCLUDE'])
avi_env.Append (CPPPATH=extra_includes)
avi_env.Library (target='#'+user_options_dict['BUILD_DIR']+'/lib/blender_avi', source=source_files)
