#!/usr/bin/python
Import ('env')

sources = env.Glob('*.c')

incs = '../include ../../blenlib ../../blenkernel ../../makesdna ../../imbuf'
incs += ' ../../windowmanager #/intern/guardedalloc #/extern/glew/include'
incs += ' ../../render/extern/include ../../makesrna'

defs = []

if env['WITH_BF_LCMS']:
	defs.append('WITH_LCMS')
if env['WITH_BF_OPENEXR']:
	defs.append('WITH_OPENEXR')

env.BlenderLib ( 'bf_editors_space_image', sources, Split(incs), defs, libtype=['core'], priority=[40] )
