#!/usr/bin/env python
#
# ***** BEGIN GPL LICENSE BLOCK *****
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
#
# The Original Code is Copyright (C) 2006, Blender Foundation
# All rights reserved.
#
# The Original Code is: all of this file.
#
# Contributor(s): Nathan Letwory.
#
# ***** END GPL LICENSE BLOCK *****

Import ('env')

sources = env.Glob('*.c')

incs = [
    '#/intern/guardedalloc',
    env['BF_GLEW_INC'],
    '#/intern/glew-mx',
    '../include',
    '../../blenfont',
    '../../blenkernel',
    '../../blenlib',
    '../../bmesh',
    '../../gpu',
    '../../imbuf',
    '../../makesdna',
    '../../makesrna',
    '../../render/extern/include',
    '../../windowmanager',
    '../../gpu',
    ]
incs = ' '.join(incs)

defs = env['BF_GL_DEFINITIONS']

if env['WITH_BF_INTERNATIONAL']:
    defs.append('WITH_INTERNATIONAL')
if env['WITH_BF_OPENEXR']:
    defs.append('WITH_OPENEXR')
if env['WITH_BF_OPENJPEG']:
    defs.append('WITH_OPENJPEG')
if env['WITH_BF_TIFF']:
    defs.append('WITH_TIFF')
if env['WITH_BF_CINEON']:
    defs.append('WITH_CINEON')
if env['WITH_BF_OIIO']:
    defs.append('WITH_OPENIMAGEIO')

if env['OURPLATFORM'] in ('win32-vc', 'win32-mingw', 'linuxcross', 'win64-vc', 'win64-mingw'):
    incs += ' ' + env['BF_PTHREADS_INC']

env.BlenderLib ( 'bf_editors_space_image', sources, Split(incs), defs, libtype=['core'], priority=[40] )
