Import ('user_options_dict')

SConscript(['avi/SConscript',
            'blenkernel/SConscript',
            'blenlib/SConscript',
            'blenloader/SConscript',
            'blenpluginapi/SConscript',
            'deflate/SConscript',
            'imbuf/SConscript',
            'img/SConscript',
            'inflate/SConscript',
            'makesdna/SConscript',
            'python/SConscript',
            'radiosity/SConscript',
            'readblenfile/SConscript',
            'readstreamglue/SConscript',
            'render/SConscript',
            'renderconverter/SConscript',
            'src/SConscript',
            'writeblenfile/SConscript',
            'writestreamglue/SConscript',
            'yafray/SConscript'])

if user_options_dict['USE_INTERNATIONAL'] == 1:
    SConscript (['ftfont/SConscript'])

if user_options_dict['USE_QUICKTIME'] == 1:
    SConscript (['quicktime/SConscript'])
