#!/usr/bin/python
Import ('env')
import sys

SConscript(['avi/SConscript',
            'blenkernel/SConscript',
            'blenlib/SConscript',
            'blenloader/SConscript',
            'blenpluginapi/SConscript',
            'gpu/SConscript',
            'imbuf/SConscript',
            'imbuf/intern/cineon/SConscript',
            'makesdna/SConscript',
            'radiosity/SConscript',
            'readblenfile/SConscript',
            'render/SConscript',
            'src/SConscript',
            'nodes/SConscript'])



if env['WITH_BF_PYTHON']:
    SConscript(['python/SConscript'])

if env['WITH_BF_YAFRAY']:
    SConscript(['yafray/SConscript'])

if env['WITH_BF_INTERNATIONAL']:
    SConscript (['ftfont/SConscript'])

if env['WITH_BF_DDS']:
    SConscript (['imbuf/intern/dds/SConscript'])

if env['WITH_BF_OPENEXR']:
    SConscript (['imbuf/intern/openexr/SConscript'])

if env['WITH_BF_QUICKTIME']:
    SConscript (['quicktime/SConscript'])
