#!/usr/bin/env python
#
# ***** BEGIN GPL LICENSE BLOCK *****
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
#
# The Original Code is Copyright (C) 2006, Blender Foundation
# All rights reserved.
#
# The Original Code is: all of this file.
#
# Contributor(s): Nathan Letwory.
#
# ***** END GPL LICENSE BLOCK *****

Import ('env')

sources = env.Glob('intern/*.c')

cflags=''
# don't add ../blenkernel back!
incs = [
    '.',
    '#/extern/wcwidth',
    '#/intern/guardedalloc',
    '../makesdna',
    env['BF_FREETYPE_INC'],
    env['BF_ZLIB_INC'],
    ]
incs = ' '.join(incs)

defs = []

if env['WITH_BF_BINRELOC']:
    incs += ' ../../../extern/binreloc/include'
    defs.append('WITH_BINRELOC')

if env['OURPLATFORM'] in ('win32-vc', 'win32-mingw', 'linuxcross', 'win64-vc', 'win64-mingw'):
    incs += ' ' + env['BF_PTHREADS_INC']
    incs += ' ../../../intern/utfconv'

if env['OURPLATFORM'] == 'linuxcross':
    if env['WITH_BF_OPENMP']:
        incs += ' ' + env['BF_OPENMP_INC']

env.BlenderLib ( 'bf_blenlib', sources, Split(incs), Split(defs), libtype=['core','player'], priority = [370,230], compileflags =cflags )
