blenlib_env = Environment ()

# Import the C flags set in the SConstruct file
Import ('cflags')
Import ('cxxflags')
Import ('defines')
Import ('extra_includes')
Import ('user_options_dict')
blenlib_env.Append (CCFLAGS = cflags)
blenlib_env.Append (CXXFLAGS = cxxflags)
blenlib_env.Append (CPPDEFINES = defines)

source_files = ['intern/BLI_dynstr.c',
                'intern/BLI_ghash.c',
                'intern/BLI_linklist.c',
                'intern/BLI_memarena.c',
                'intern/arithb.c',
                'intern/dynlib.c',
                'intern/fileops.c',
                'intern/gsqueue.c',
                'intern/matrixops.c',
                'intern/noise.c',
                'intern/psfont.c',
                'intern/rand.c',
                'intern/rct.c',
                'intern/scanfill.c',
                'intern/storage.c',
                'intern/time.c',
                'intern/util.c',
                'intern/vectorops.c',
                'intern/freetypefont.c',
                'intern/winstuff.c']


blenlib_env.Append (CPPPATH = ['.',
                               '../makesdna',
                               '../blenkernel',
                               '#/intern/guardedalloc',
                               '../include'])

if user_options_dict['USE_INTERNATIONAL'] == 1:
    blenlib_env.Append (CPPDEFINES = 'WITH_FREETYPE2')

blenlib_env.Append (CPPPATH = extra_includes)
blenlib_env.Prepend (CPPPATH = user_options_dict['FREETYPE_INCLUDE'])
blenlib_env.Library (target='#'+user_options_dict['BUILD_DIR']+'/lib/blender_blenlib', source=source_files)
