#!/usr/bin/python
Import ('env')

sources = env.Glob('intern/*.c')

incs = '. ../makesdna ../blenkernel #/intern/guardedalloc ../include'
incs += ' ' + env['BF_FREETYPE_INC']
incs += ' ' + env['BF_ZLIB_INC']
incs += ' ' + env['BF_SDL_INC']
defs = ''

if env['WITH_BF_INTERNATIONAL'] == 1:
    defs = 'WITH_FREETYPE2'

env.BlenderLib ( 'blender_blenlib', sources, Split(incs), Split(defs), libtype='core', priority = 85 )
