#!/usr/bin/python
import sys
import os

Import ('env')
cflags = '-Wall'
defines = []
root_build_dir=env['BF_BUILDDIR']

source_files = env.Glob('*.c')

# making rna_access.c part of both makesrna and blender seems to
# give conflict, how to solve?
source_files.remove('rna_access.c')

generated_files = source_files[:]
generated_files.remove('rna_define.c')
generated_files.remove('makesrna.c')

generated_files = [filename[:-2] + '_gen.c' for filename in generated_files]

makesrna_tool = env.Clone()
rna = env.Clone()
makesrna_tool.Append(CCFLAGS = '-DBASE_HEADER="\\"source/blender/makesrna/\\"" ')

makesrna_tool.Append (CPPPATH = ['#/intern/guardedalloc',
                                 '../../blenlib',
                                 '../../blenkernel',
                                 '../../makesdna',
                                 '../../makesrna',
								 '../../windowmanager'])

if env['OURPLATFORM'] == 'linuxcross':
	USE_WINE = True # when cross compiling on linux 64bit this is useful
else:
	USE_WINE = False

if not USE_WINE:
	if env['OURPLATFORM'] == 'linuxcross':
		makesdna_tool.Replace(CC='gcc')
		makesdna_tool.Replace(AR='ar')
		makesdna_tool.Replace(LINK='gcc')

if sys.platform != 'cygwin':
    makesrna_tool.Append (CCFLAGS = cflags)
makesrna_tool.Append (CPPDEFINES = defines)

libdir = root_build_dir+'/lib'
if not (root_build_dir[0]==os.sep or root_build_dir[1]==':'):
	libdir = '#' + libdir

makesrna_tool.Append (LIBPATH = libdir)

if env['BF_PROFILE']:
	makesrna_tool.Append (LINKFLAGS = env['BF_PROFILE_FLAGS'])

if env['BF_DEBUG']:
	makesrna_tool.Append(CFLAGS = env['BF_DEBUG_CFLAGS'])
	makesrna_tool.Append(CCFLAGS = env['BF_DEBUG_CCFLAGS'])
	if env['OURPLATFORM'] == 'win32-vc':
		makesrna_tool.Append(LINKFLAGS = ['/DEBUG','/PDB:makesrna.pdb'])

targetpath = root_build_dir+'/makesrna'
if not (root_build_dir[0]==os.sep or root_build_dir[1]==':'):
	targetpath = '#' + targetpath

if env['OURPLATFORM'] == 'linux2' and root_build_dir[0]==os.sep:
    makesrna = makesrna_tool.Program (target = targetpath, source = source_files, LIBS=['bf_guardedalloc', 'bf_dna'])
else:
    makesrna = makesrna_tool.Program (target = targetpath, source = source_files, LIBS=['bf_guardedalloc', 'bf_dna'])

rna_dict = rna.Dictionary()
rna.Depends (generated_files, makesrna)

# this seems bad, how to retrieve it from scons?
build_dir = root_build_dir + '/source/blender/makesrna/intern/'

if env['OURPLATFORM'] != 'linuxcross':
    rna.Command (generated_files, '', root_build_dir+os.sep+"makesrna " + build_dir)
else:
    rna.Command (generated_files, '', root_build_dir+os.sep+"makesrna.exe "  + build_dir)
	
    if USE_WINE:
        rna.Command (generated_files, '', 'wine ' + root_build_dir+os.sep+"makesrna.exe "  + build_dir)
    else:
        rna.Command (generated_files, '', root_build_dir+os.sep+"makesrna.exe "  + build_dir)


obj = ['intern/rna_access.c']
for generated_file in generated_files:
	obj += ['intern/' + generated_file]

Return ('obj')

