Import ('extra_includes')
Import ('user_options_dict')
Import ('library_env')

readstrgl_env = library_env.Copy ()

source_files = ['intern/BLO_readStreamGlue.c',
                'intern/BLO_readStreamGlueLoopBack.c']

readstrgl_env.Append (CPPPATH = ['.',
                                 '../../kernel/gen_messaging',
                                 '../blenloader',
                                 '../inflate'])

readstrgl_env.Append (CPPPATH = user_options_dict['Z_INCLUDE'])
readstrgl_env.Append (CPPPATH = extra_includes)
readstrgl_env.Library (target='#'+user_options_dict['BUILD_DIR']+'/lib/blender_readstreamglue', source=source_files)
