#!/usr/bin/python
import sys
Import ('env')

sources = env.Glob('intern/*.c')

incs = '. intern ../blenkernel ../blenlib ../makesdna ../ftfont'

env.BlenderLib ( 'bf_blenfont', sources, Split(incs), Split(defs), libtype=['core'], priority=[210] )
