#!/usr/bin/python
import sys
Import ('env')

sources = env.Glob('intern/*.c')

incs = '. intern  #/intern/guardedalloc ../blenkernel ../blenlib ../makesdna ../ftfont ../editors/include'
incs += ' ' + env['BF_FTGL_INC']
incs += ' ' + env['BF_FREETYPE_INC']
incs += ' ' + env['BF_GETTEXT_INC']

defs = ''

if env['WITH_BF_INTERNATIONAL']:
	defs += ' WITH_FREETYPE2'

env.BlenderLib ( 'bf_blenfont', sources, Split(incs), Split(defs), libtype=['core'], priority=[210] )
