#!/usr/bin/python
Import('env')

sources = env.Glob('intern/*.cpp') + env.Glob('intern/*.inl')

incs = 'intern ../container ../moto/include ../memutil intern/blender extern'

env.BlenderLib ('blender_BSP', sources, Split(incs) , [], libtype='blender', priority=15)
