/* SPDX-FileCopyrightText: 2011-2022 Blender Foundation
 *
 * SPDX-License-Identifier: Apache-2.0 */

#include "node_fresnel.h"
#include "node_math.h"
#include "stdcycles.h"

shader node_glass_bsdf(color Color = 0.8,
                       string distribution = "ggx",
                       float Roughness = 0.2,
                       float Anisotropy = 0.0,
                       float Rotation = 0.0,
                       float IOR = 1.45,
                       float ThinFilmThickness = 0.0,
                       float ThinFilmIOR = 1.33,
                       normal Normal = N,
                       normal Tangent = 0.0,
                       output closure color BSDF = 0)
{
  color base_color = max(Color, color(0.0));
  float alpha = sqr(clamp(Roughness, 0.0, 1.0));
  float eta = max(IOR, 1e-5);
  float thinfilm_ior = backfacing() ? ThinFilmIOR / eta : ThinFilmIOR;
  eta = backfacing() ? 1.0 / eta : eta;
  color F0 = F0_from_ior(eta);
  color F90 = color(1.0);
  float alpha_x, alpha_y;
  float aniso = clamp(Anisotropy, -0.99, 0.99);

  /* rotate tangent around normal */
  vector T = Tangent;

  if (abs(aniso) <= 1e-4) {
    alpha_x = alpha;
    alpha_y = alpha;
  }
  else {
    if (Rotation != 0.0) {
      T = rotate(T, Rotation * M_2PI, point(0.0, 0.0, 0.0), Normal);
    }

    if (aniso < 0.0) {
      alpha_x = alpha / (1.0 + aniso);
      alpha_y = alpha * (1.0 + aniso);
    }
    else {
      alpha_x = alpha * (1.0 - aniso);
      alpha_y = alpha / (1.0 - aniso);
    }
  }

  BSDF = generalized_schlick_bsdf(Normal,
                                  T,
                                  base_color,
                                  base_color,
                                  alpha_x,
                                  alpha_y,
                                  F0,
                                  F90,
                                  -eta,
                                  distribution,
                                  "thinfilm_thickness",
                                  ThinFilmThickness,
                                  "thinfilm_ior",
                                  thinfilm_ior);
}
