/* SPDX-FileCopyrightText: 2011-2022 Blender Foundation
 *
 * SPDX-License-Identifier: Apache-2.0 */

#include "stdcycles.h"

shader node_refraction_bsdf(color Color = 0.8,
                            string distribution = "ggx",
                            float Roughness = 0.2,
                            float IOR = 1.45,
                            normal Normal = N,
                            output closure color BSDF = 0)
{
  float eta = max(IOR, 1e-5);
  float roughness = Roughness * Roughness;

  BSDF = Color * microfacet(distribution, Normal, roughness, eta, 1);
}
