#!/usr/bin/python
Import ('env')

sources = env.Glob('*.c')

incs = '../include ../../blenlib ../../blenkernel ../../makesdna ../../imbuf'
incs += ' #/intern/guardedalloc'

env.BlenderLib ( 'bf_space_view3d', sources, Split(incs), [], libtype=['core','intern'], priority=[5, 25] )
