#!/usr/bin/python
Import ('env')

sources = env.Glob('*.cpp')

# relative paths to include dirs, space-separated, string
incs = '../blenlib ../blenkernel %s/COLLADAStreamWriter/include %s/COLLADABaseUtils/include' % (env['BF_OPENCOLLADA'], env['BF_OPENCOLLADA']) + ' ../makesdna'

env.BlenderLib ('bf_collada', sources, Split(incs), [], libtype='core', priority=200 )

