#!/usr/bin/env python
#
# ***** BEGIN GPL LICENSE BLOCK *****
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
#
# The Original Code is Copyright (C) 2006, Blender Foundation
# All rights reserved.
#
# The Original Code is: all of this file.
#
# Contributor(s): Arystanbek Dyussenov, Nathan Letwory.
#
# ***** END GPL LICENSE BLOCK *****

Import ('env')

sources = env.Glob('*.cpp')
defs = []

# TODO sanitize inc path building
# relative paths to include dirs, space-separated, string
incs = [
    '../ikplugin',
    '#/intern/iksolver/extern',
    '../blenlib',
    '../blenfont',
    '../blenkernel',
    '../windowmanager',
    '../makesdna',
    '../makesrna',
    '../editors/include',
    '../imbuf',
    '../bmesh',
    '#/intern/guardedalloc',
]
incs += [
    env['BF_OPENCOLLADA_INC'] + '/COLLADAStreamWriter',
    env['BF_OPENCOLLADA_INC'] + '/COLLADABaseUtils',
    env['BF_OPENCOLLADA_INC'] + '/COLLADAFramework',
    env['BF_OPENCOLLADA_INC'] + '/COLLADASaxFrameworkLoader',
    env['BF_OPENCOLLADA_INC'] + '/GeneratedSaxParser',
]

if env['BF_BUILDINFO']:
    defs.append('WITH_BUILDINFO')

if env['WITH_BF_INTERNATIONAL']:
    defs.append('WITH_INTERNATIONAL')

env.BlenderLib ('bf_collada', sources, incs, defs, libtype='core', priority=200 )
