Import ('user_options_dict')
Import ('library_env')

img_env = library_env.Copy ()

source_files = ['intern/IMG_Api.cpp',
                'intern/IMG_BrushRGBA32.cpp',
                'intern/IMG_CanvasRGBA32.cpp',
                'intern/IMG_Line.cpp',
                'intern/IMG_Pixmap.cpp',
                'intern/IMG_PixmapRGBA32.cpp',
                'intern/IMG_Rect.cpp']

img_env.Library (target='#'+user_options_dict['BUILD_DIR']+'/lib/blender_img', source=source_files)
