Import ('extra_includes')
Import ('user_options_dict')
Import ('library_env')

wrstrgl_env = library_env.Copy ()

source_files = ['intern/BLO_dumpFromMemory.c',
                'intern/BLO_getPubKey.c',
                'intern/BLO_streamGlueControl.c',
                'intern/BLO_writeStreamGlue.c']

wrstrgl_env.Append (CPPPATH = ['.',
                               '../readstreamglue',
                               '../deflate',
                               '../writeblenfile',
                               '../../kernel/gen_messaging'])
wrstrgl_env.Append (CPPPATH = user_options_dict['Z_INCLUDE'])

wrstrgl_env.Append (CPPPATH = extra_includes)
wrstrgl_env.Library (target='#'+user_options_dict['BUILD_DIR']+'/lib/blender_writestreamglue', source=source_files)
