#!/usr/bin/python
Import ('env')

SConscript(['BlenderRoutines/SConscript',
            'Converter/SConscript',
            'Expressions/SConscript', #310
            'GameLogic/SConscript',
            'Ketsji/SConscript',
            'Ketsji/KXNetwork/SConscript',
            'Network/SConscript',
            'Network/LoopBackNetwork/SConscript',
            'Physics/common/SConscript',
            'Physics/Dummy/SConscript',
            'Rasterizer/SConscript',
            'Rasterizer/RAS_OpenGLRasterizer/SConscript',
            'SceneGraph/SConscript',
            'Physics/Bullet/SConscript'
            ])

if env['WITH_BF_PYTHON']:
    SConscript(['VideoTexture/SConscript'])

if env['WITH_BF_PLAYER']:
    SConscript(['GamePlayer/SConscript'])
