Import ('user_options_dict')

SConscript(['BlenderRoutines/SConscript',
            'Converter/SConscript',
            'Expressions/SConscript',
            'GameLogic/SConscript',
            'Ketsji/SConscript',
            'Ketsji/KXNetwork/SConscript',
            'Network/SConscript',
            'Network/LoopBackNetwork/SConscript',
            'Physics/common/SConscript',
            'Physics/Dummy/SConscript',
            'Rasterizer/SConscript',
            'Rasterizer/RAS_OpenGLRasterizer/SConscript',
            'SceneGraph/SConscript'])

if user_options_dict['USE_PHYSICS'] == 'solid':
    SConscript(['Physics/Sumo/SConscript'])

if user_options_dict['USE_PHYSICS'] == 'ode':
    SConscript(['Physics/BlOde/SConscript'])
