#!/usr/bin/python
Import ('env')

sources = env.Glob('intern/source/*.c')

incs = 'extern/include ../blenlib ../blenkernel ../makesdna ../editors/include'
incs += ' #/intern/guardedalloc ../render/extern/include'
incs += ' ../render/intern/include'

incs += ' ' + env['BF_OPENGL_INC']

env.BlenderLib ( 'bf_radiosity', sources, Split(incs), [], libtype='core', priority=60 )
