Import ('user_options_dict')
Import ('library_env')

readblenfile_env = library_env.Copy ()

source_files = ['intern/BLO_readblenfile.c']

readblenfile_env.Append (CPPPATH = ['.',
                                    '../readstreamglue',
                                    '../blenloader',
                                    '../blenkernel',
                                    '../../kernel/gen_messaging'])

readblenfile_env.Library (target='#'+user_options_dict['BUILD_DIR']+'/lib/blender_readblenfile', source=source_files)
