readblenfile_env = Environment()

# Import the C flags set in the SConstruct file
Import ('cflags')
Import ('cxxflags')
Import ('defines')
Import ('user_options_dict')
readblenfile_env.Append (CCFLAGS = cflags)
readblenfile_env.Append (CXXFLAGS = cxxflags)
readblenfile_env.Append (CPPDEFINES = defines)

source_files = ['intern/BLO_readblenfile.c']

readblenfile_env.Append (CPPPATH = ['.',
                                    '../readstreamglue',
                                    '../blenloader',
                                    '../blenkernel',
                                    '../../kernel/gen_messaging'])

readblenfile_env.Library (target='#'+user_options_dict['BUILD_DIR']+'/lib/blender_readblenfile', source=source_files)
