/**
 * $Id$
 *
 * ***** BEGIN GPL LICENSE BLOCK *****
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 *
 * ***** END GPL LICENSE BLOCK *****
 */

#include "curve_intern.h"
 
char *ED_lorem = 
"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. "
"Aliquam tristique interdum sem. "
"Nullam pretium, tortor non euismod varius, nulla odio sodales nulla, at bibendum lorem metus sed nulla. "
"Vestibulum in lectus at pede blandit viverra. "
"Fusce scelerisque ipsum nec enim. "
"Fusce euismod nunc id enim. "
"In venenatis cursus arcu. "
"Aenean quis dui. "
"Maecenas laoreet. "
"Nulla tempor, arcu pulvinar pretium suscipit, tortor wisi dapibus libero, id ornare felis ipsum suscipit purus. "
"Maecenas ipsum. "
"Morbi cursus. "
"Vestibulum diam purus, commodo et, convallis eu, posuere at, ligula. "
"Nulla aliquam aliquet lorem. "
"Nunc et mauris hendrerit est bibendum suscipit. "
"Donec pellentesque libero eu nisl. "
"Pellentesque eget libero. "
"Donec tempus ipsum sed quam. "
"Sed blandit nunc quis enim. "
"Quisque lectus diam, adipiscing hendrerit, placerat non, pulvinar id, felis. "
"In congue magna sit amet urna. "
"Nunc non augue sed nisl dictum laoreet. "
"Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. "
"In venenatis dapibus massa. "
"Nulla hendrerit sapien et quam. "
"Nunc ac magna lobortis tellus tincidunt posuere. "
"Cras augue mauris, mattis lobortis, fermentum at, semper ac, tellus. "
"Cras vitae ligula sit amet sem posuere iaculis. "
"Aliquam condimentum eleifend felis. "
"Ut sit amet sapien. "
"Suspendisse potenti. "
"Mauris urna. "
"Ut eu enim eu ante porta vestibulum. "
"Aenean scelerisque est ac felis. "
"Suspendisse auctor. "
"Nunc pellentesque. "
"Morbi laoreet ante et nibh. "
"Donec feugiat arcu eget enim. "
"Morbi vehicula tortor ac ipsum. "
"Quisque lacus arcu, elementum ac, faucibus vel, posuere id, est. "
"Proin commodo gravida sem. "
"Vivamus tincidunt vehicula libero. "
"Phasellus wisi. "
"Maecenas pretium tellus eu sapien. "
"Nunc sit amet nunc. "
"In hac habitasse platea dictumst. "
"Aenean dictum neque sed tortor. "
"Donec et erat. "
"Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed justo turpis, scelerisque ut, mattis sit amet, ornare rutrum, massa. "
"Vestibulum bibendum enim sit amet velit. "
"Vivamus tellus ipsum, luctus ut, consectetuer vitae, dignissim non, ligula. "
"Phasellus lacinia wisi at est. "
"Donec elit wisi, commodo non, placerat in, convallis id, elit. "
"Nunc dolor dolor, vestibulum id, bibendum vitae, lacinia id, erat. "
"Cras sit amet eros. "
"Suspendisse suscipit lobortis lectus. "
"Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. "
"Cras orci. "
"Praesent massa urna, lobortis semper, auctor a, pretium vitae, tellus. "
"Curabitur at purus. "
"Morbi tortor quam, imperdiet venenatis, egestas a, cursus eu, est. "
"Nunc interdum lectus sit amet libero. "
"Quisque dignissim placerat ligula. "
"Nunc porttitor posuere arcu. "
"Mauris faucibus quam at massa. "
"Vivamus sodales aliquet mauris. "
"In id ante. "
"Pellentesque varius ipsum in arcu. "
"Fusce mauris lacus, tristique ac, lobortis quis, lobortis luctus, pede. "
"Sed wisi. "
"Vestibulum mattis. "
"Maecenas hendrerit sem nec purus. "
"Proin id quam. "
"Cras nec mauris. "
"Integer orci. "
"Nullam dui sem, molestie sed, egestas quis, cursus in, magna. "
"Mauris neque lacus, consectetuer nec, sagittis eu, porttitor eget, dui. "
"Fusce consectetuer. "
"Donec nec tellus quis leo lobortis ullamcorper. "
"Etiam metus urna, aliquet pretium, ultrices eu, cursus ut, turpis. "
"Morbi bibendum vehicula lectus. "
"Sed non ante vitae arcu pellentesque tempor. "
"Fusce sed ligula in sem tempor imperdiet. "
"Aliquam vel est. "
"Phasellus sollicitudin sollicitudin nibh. "
"Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. "
"Sed vel leo nec eros blandit imperdiet. "
"Nulla facilisi. "
"Suspendisse lobortis, dui ut fringilla hendrerit, justo purus ullamcorper ligula, ultricies ultrices dolor enim in libero. "
"Sed elementum, pede eget porta convallis, dui nulla dignissim pede, eget vehicula odio ante at sem. "
"Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. "
"Sed ullamcorper tincidunt ipsum. "
"Fusce risus nibh, accumsan sit amet, tempus eget, tristique ac, neque. "
"Sed quis lorem ut tortor facilisis fermentum. "
"Fusce pulvinar quam sit amet ipsum. "
"Morbi ac elit quis tellus malesuada blandit. "
"Maecenas suscipit sollicitudin sem. "
"Nam sed eros vel lacus lobortis congue. "
"Proin interdum nunc lobortis orci. "
"Donec egestas enim eu odio. "
"Vestibulum id metus. "
"Pellentesque auctor, sem varius luctus tempus, libero magna cursus neque, et porttitor diam diam quis purus. "
"Vestibulum sit amet dolor. "
"Nulla in magna. "
"Cras id diam at lectus faucibus placerat. "
"Nunc porta posuere sapien. "
"Etiam scelerisque. "
"Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. "
"Aliquam pellentesque mi sed tortor. "
"Maecenas eleifend diam non urna. "
"Donec luctus pharetra tellus. "
"Proin ac ipsum eget libero bibendum volutpat. "
"Cras id tellus. "
"Nulla non risus. "
"In dolor. "
"Fusce scelerisque quam in massa ultrices porta. "
"Morbi ut dolor eu massa egestas condimentum. "
"Mauris vulputate. "
"In hac habitasse platea dictumst. "
"Suspendisse potenti. "
"Mauris vehicula leo in tortor. "
"Mauris vel erat a urna laoreet semper. "
"Pellentesque ut metus ac tellus commodo eleifend. "
"Suspendisse quis urna. "
"Curabitur lacinia dignissim dui. "
"Nam nec ante. "
"In id enim. "
"Aenean mattis enim. "
"In ut neque porttitor risus hendrerit tincidunt. "
"Suspendisse potenti. "
"Ut vestibulum lectus vitae tortor. "
"Duis velit. "
"Nulla facilisi. "
"Integer sit amet urna. "
"Cras varius tortor in pede. "
"Sed facilisis. "
"Praesent lacinia libero nec nibh. "
"Donec aliquam risus non nisl. "
"Nam a nunc et felis tempor feugiat. "
"Nunc metus. "
"Vestibulum euismod, metus in semper laoreet, urna ipsum pharetra lorem, sed ultricies magna lorem sit amet wisi. "
"Sed wisi. "
"Nullam facilisis elit sed nisl. "
"Phasellus mattis leo nec massa. "
"Aenean malesuada. "
"Cras wisi erat, lobortis nec, cursus eget, lobortis at, libero. "
"In massa nisl, rutrum non, cursus nec, faucibus sed, lacus. "
"Pellentesque malesuada. "
"Cras euismod, neque ac suscipit tempus, velit lorem luctus elit, dapibus rhoncus wisi est ut sem. "
"Proin vulputate enim in eros elementum accumsan. "
"Ut lorem nisl, hendrerit et, interdum nec, lacinia in, dolor. "
"Duis nec quam. "
"Praesent velit felis, posuere id, luctus quis, laoreet ut, ipsum. "
"Praesent eget arcu. "
"Mauris massa felis, ornare non, ultrices id, tristique in, elit. "
"Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. "
"Phasellus vulputate, mi ac bibendum facilisis, libero enim suscipit leo, non nonummy pede diam eget nibh. "
"Sed tempus. "
"Aenean interdum suscipit dui. "
"Aliquam erat volutpat. "
"Ut malesuada. "
"Nam commodo, nulla ut fringilla rutrum, orci elit viverra diam, vitae mollis odio odio et purus. "
"Aliquam erat volutpat. "
"Sed aliquet lobortis ipsum. "
"In ut est. "
"Etiam condimentum. "
"Vestibulum pellentesque tortor pulvinar lacus. "
"Aenean orci. "
"Suspendisse lacus nulla, nonummy a, dictum vitae, egestas quis, eros. "
"Donec auctor gravida nisl. "
"Cras ac est rutrum augue pulvinar ornare. "
"Phasellus mauris nibh, vulputate in, rhoncus imperdiet, dapibus eget, lacus. "
"Nam nunc mauris, suscipit at, ultricies a, facilisis at, tellus. "
"Nam accumsan mollis libero. "
"Vivamus condimentum mattis est. "
"Donec lacus. "
"Nullam ac sapien id massa lobortis molestie. "
"Pellentesque elementum. "
"Proin ut purus. "
"Integer et sapien quis turpis commodo mollis. "
"Nulla consequat. "
"Proin a wisi ut tellus blandit elementum. "
"Aliquam nulla lorem, bibendum ac, malesuada vel, elementum et, metus. "
"Phasellus egestas nibh et ligula. "
"Vivamus diam odio, lacinia quis, malesuada quis, sollicitudin ut, eros. "
"Phasellus aliquet lorem ac ipsum. "
"Sed cursus tellus ac orci. "
"Phasellus at nulla. "
"Donec porta sodales ante. "
"Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. "
"Sed id lectus at massa ullamcorper tristique. "
"Suspendisse porttitor lacus. "
"In hac habitasse platea dictumst. "
"Nunc non turpis. "
"Sed sagittis. "
"Morbi laoreet scelerisque dui. "
"Nam arcu tellus, tempor vitae, vestibulum et, imperdiet ut, velit. "
"In sit amet augue a arcu volutpat suscipit. "
"Donec dictum ultrices lectus. "
"Phasellus a purus et orci dictum lacinia. "
"Ut leo. "
"Cras semper, lorem sit amet tincidunt congue, justo eros varius pede, in bibendum turpis lectus non eros. "
"Phasellus quam. "
"Suspendisse mattis sollicitudin magna. "
"Aenean facilisis diam vel nisl nonummy condimentum. "
"Suspendisse vel dolor. "
"Vestibulum nonummy. "
"Mauris imperdiet semper ante. "
"Maecenas vulputate eros. "
"Vestibulum ac dolor. "
"Fusce risus metus, aliquet eget, facilisis et, feugiat vel, orci. "
"Ut at nunc id ante sodales vulputate. "
"Duis tristique mattis ante. "
"Vestibulum neque mauris, laoreet id, congue interdum, aliquet ut, diam. "
"Nulla volutpat blandit magna. "
"Donec accumsan congue diam. "
"Etiam vel dui eget nisl tempor varius. "
"Cras dictum massa sed enim. "
"Cras urna tortor, fringilla ac, ullamcorper in, euismod vel, arcu. "
"Morbi posuere luctus augue. "
"Aliquam dui dui, adipiscing in, lobortis eu, luctus eu, nulla. "
"Cras velit pede, ullamcorper sit amet, feugiat in, auctor vitae, ante. "
"Suspendisse dictum fringilla mauris. "
"In a nibh. "
"Donec ac ligula. "
"In quam. "
"Praesent vitae urna ultricies sem aliquam placerat. "
"Aliquam erat volutpat. "
"Nam est. "
"Donec faucibus sodales metus. "
"Ut congue. "
"Donec arcu tellus, pharetra ac, vulputate ac, mollis sed, lectus. "
"Nulla facilisi. "
"Nullam volutpat nunc et felis. "
"Sed pede odio, tincidunt in, volutpat malesuada, feugiat gravida, nulla. "
"Nulla aliquam pede vitae arcu. "
"Proin velit elit, nonummy sit amet, elementum vitae, varius vitae, dolor. "
"Donec rutrum ipsum eu mi. "
"Aliquam et sem. "
"In adipiscing rhoncus velit. "
"Nam viverra scelerisque arcu. "
"Aliquam sem. "
"Sed tincidunt nulla quis massa. "
"Mauris faucibus tempus nunc. "
"Phasellus condimentum. "
"Curabitur aliquet iaculis sapien. "
"Nunc rhoncus, odio vitae bibendum dignissim, tellus libero commodo ipsum, ut sollicitudin nisl nisl vel justo. "
"Nulla facilisi. "
"Praesent blandit enim ut justo. "
"Proin elementum, elit eget accumsan pulvinar, orci quam auctor neque, sed convallis diam purus vel felis. "
"Sed orci leo, eleifend vel, blandit non, semper eu, purus. "
"Proin bibendum, libero ac consectetuer commodo, eros sapien blandit nisl, eu eleifend nibh nibh vel lectus. "
"Vivamus placerat. "
"Integer odio dolor, pharetra non, sodales id, viverra eget, diam. "
"Nunc mauris magna, egestas quis, feugiat id, fermentum viverra, mi. "
"Aenean suscipit nisl non nunc. "
"Proin quis lectus ac tellus nonummy commodo. "
"Nunc eget diam ac elit vestibulum auctor. "
"Etiam vulputate, odio sed lacinia consequat, justo mi vulputate purus, sit amet euismod libero metus sed tortor. "
"Maecenas ac elit sed lorem vulputate gravida. "
"Proin lectus eros, ullamcorper id, volutpat quis, condimentum tincidunt, sapien. "
"Sed et massa eget lorem aliquet tempus. "
"Duis porttitor nisl non risus. "
"Nam id quam. "
"Nullam est. "
"Proin orci diam, posuere et, pharetra commodo, dictum vel, enim. "
"Proin eget erat. "
"Donec nisl. "
"Maecenas auctor velit ut pede. "
"Nunc vitae lectus nec libero tincidunt hendrerit. "
"Quisque varius, erat ultrices ultrices euismod, purus lacus dictum eros, at condimentum enim dui nec magna. "
"Morbi diam. "
"Phasellus sed est. "
"Phasellus nec libero in arcu fringilla sollicitudin. "
"In rutrum nisl at arcu. "
"Nulla facilisi. "
"Mauris dignissim. "
"Etiam est mauris, pharetra sed, viverra et, tincidunt sed, neque. "
"Ut at lectus id nibh luctus ornare. "
"Mauris varius porttitor risus. "
"Ut vulputate aliquet risus. "
"Vestibulum luctus neque sit amet nunc. "
"Duis fermentum nibh. "
"Pellentesque dapibus. "
"Proin eros libero, aliquam non, condimentum a, sodales ut, turpis. "
"Integer accumsan mi sed lorem. "
"Vestibulum pellentesque sodales nisl. "
"Nulla eu justo quis dui pretium rhoncus. "
"Praesent viverra commodo mi. "
"Maecenas dolor libero, viverra a, elementum vitae, aliquet vitae, dui. "
"Mauris convallis lectus et mi. "
"Mauris sagittis. "
"Sed arcu. "
"Pellentesque auctor. "
"Donec pellentesque purus non tellus. "
"Ut leo wisi, ultrices sit amet, ultrices eu, gravida ac, libero. "
"Mauris fermentum dapibus diam. "
"Integer quis lacus dapibus odio pellentesque varius. "
"Fusce pede quam, vehicula ut, pulvinar et, tincidunt sed, felis. "
"Curabitur eros enim, vulputate sed, aliquam ac, euismod ac, erat. "
"Ut dignissim, lacus a interdum iaculis, enim orci posuere nunc, nec ultricies lectus risus in odio. "
"Etiam et massa id dui commodo vehicula. "
"Nunc blandit tortor quis dui. "
"Quisque nisl. "
"Sed venenatis blandit ligula. "
"Fusce viverra imperdiet magna. "
"Donec eget nunc quis est pharetra lobortis. "
"Vestibulum quis lectus. "
"Mauris vel orci lobortis nunc fermentum bibendum. "
"Pellentesque eget leo. "
"Morbi vel urna sit amet erat fermentum facilisis. "
"Sed vulputate, libero et sollicitudin congue, wisi lectus sodales dolor, eget molestie magna orci vel tellus. "
"Sed tempor ante et enim. "
"Mauris elit. "
"Curabitur ullamcorper vehicula massa. "
"Sed viverra. "
"Duis nulla. "
"Nam bibendum. "
"Nam tortor lorem, ullamcorper vitae, dictum sed, posuere eu, justo. "
"Aliquam adipiscing arcu vitae turpis. "
"Donec malesuada posuere libero. "
"Ut sed tellus. "
"Fusce sed nunc eget nisl dapibus malesuada. "
"Suspendisse potenti. "
"Integer tristique libero et metus. "
"Vivamus posuere. "
"Maecenas non sem non quam fermentum blandit. "
"Duis risus tellus, rutrum vitae, imperdiet nec, malesuada nec, ipsum. "
"Nunc quam dolor, luctus eget, placerat non, rhoncus at, tellus. "
"Duis pede lectus, mattis adipiscing, tempor ut, porta at, mi. "
"Pellentesque risus nulla, sodales sed, interdum id, nonummy vitae, ligula. "
"Morbi pulvinar pede ut massa. "
"Nunc risus mauris, tincidunt et, faucibus eu, suscipit vel, orci. "
"In faucibus felis in arcu. "
"Nulla sit amet elit. "
"Nulla erat sapien, sagittis eget, dignissim eget, viverra eu, felis. "
"Nam ac ipsum. "
"Suspendisse vulputate turpis vel sem lacinia ullamcorper. "
"Mauris ornare ipsum sed ligula. "
"Duis facilisis neque quis orci. "
"Nullam et erat et orci lacinia pellentesque. "
"Donec ac ipsum. "
"Duis molestie ipsum ac arcu. "
"Aenean congue accumsan ante. "
"Integer bibendum, leo ut ornare aliquam, nunc erat condimentum arcu, ut pulvinar mi augue et nulla. "
"Quisque lacinia aliquet wisi. "
"Vivamus nec dui. "
"Etiam wisi leo, euismod vitae, vulputate a, dictum vitae, quam. "
"Quisque quis tortor. "
"Etiam interdum. "
"In massa erat, porttitor sed, tincidunt vel, vehicula fringilla, augue. "
"Nulla vel urna. "
"In libero mi, pretium sed, mattis tempus, sagittis sed, massa. "
"Suspendisse quam wisi, fermentum quis, sagittis at, consequat eget, odio. "
"Nullam imperdiet, purus quis aliquam cursus, turpis odio egestas justo, placerat gravida turpis wisi vel tortor. "
"Nunc ultricies porta purus. "
"Proin elementum erat ac orci. "
"Ut vel magna nec mi feugiat tincidunt. "
"Ut ligula. "
"Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec et magna in diam porta nonummy. "
"Maecenas ut sem in turpis fermentum viverra. "
"Suspendisse at orci. "
"Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. "
"Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Pellentesque rutrum eleifend justo. "
"Nullam vitae pede. "
"Donec condimentum nibh et odio. "
"Sed et metus. "
"Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. "
"Nam tempus. "
"Sed ac wisi. "
"In hac habitasse platea dictumst. "
"Sed sed wisi. "
"Ut facilisis tellus non ligula. "
"Integer metus. "
"In lacinia dui. "
"Curabitur ornare. "
"Mauris vel urna. "
"Nam consectetuer dignissim urna. "
"Nunc elementum porttitor erat. "
"Sed blandit, risus non commodo nonummy, ligula erat fermentum nibh, eu facilisis ante neque sed sem. "
"Etiam scelerisque justo eget wisi. "
"Nunc dignissim. "
"Proin pulvinar quam non lectus. "
"Proin ut turpis quis augue pellentesque dictum. "
"Fusce et lorem. "
"Aliquam urna lacus, blandit sed, vestibulum sit amet, placerat et, dolor. "
"Curabitur auctor erat nec lorem. "
"Phasellus urna wisi, lacinia ut, molestie tincidunt, condimentum id, odio. "
"Curabitur convallis ullamcorper justo. "
"Donec vestibulum est ac quam. "
"Nullam vitae elit eu massa varius vulputate. "
"Nulla facilisi. "
"Suspendisse potenti. "
"Praesent non libero. "
"Nullam tristique massa id magna viverra commodo. "
"Vestibulum libero tortor, luctus ac, viverra congue, consectetuer vel, libero. "
"Aenean arcu augue, luctus id, laoreet pulvinar, dictum sed, lectus. "
"Donec vestibulum volutpat dolor. "
"Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. "
"Pellentesque augue turpis, laoreet nec, malesuada at, nonummy vitae, nibh. "
"Etiam orci sapien, congue in, porttitor sit amet, rutrum vel, nibh. "
"Integer eu lorem. "
"Mauris pretium leo et elit. "
"In nonummy ultricies sapien. "
"Mauris varius. "
"Mauris sed libero. "
"Curabitur ullamcorper elit eu purus. "
"Vestibulum velit pede, semper sit amet, lobortis vitae, tincidunt vel, dui. "
"Nulla neque ante, sagittis eu, vestibulum et, lacinia a, libero. "
"Morbi sit amet wisi. "
"Pellentesque non felis quis arcu bibendum ornare. "
"Aenean enim metus, commodo eu, hendrerit nonummy, euismod ut, quam. "
"Nulla eleifend nisl quis dolor. "
"Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. "
"Maecenas pellentesque massa in erat molestie molestie. "
"Mauris dignissim dapibus libero. "
"Sed sed risus id neque dictum ornare. "
"Sed eu ligula at felis sodales accumsan. "
"Sed interdum, urna non pharetra hendrerit, quam mi ornare libero, id fringilla tortor orci non velit. "
"Aliquam nec risus. "
"Donec at nunc vitae tellus molestie vestibulum. "
"Pellentesque vel justo. "
"Duis ligula libero, vulputate quis, adipiscing bibendum, feugiat vitae, velit. "
"Vivamus et arcu. "
"Fusce eget quam. "
"Ut ante. "
"Suspendisse feugiat metus non ipsum. "
"Nulla tempus leo ut mi. "
"Curabitur vitae nisl. "
"Vivamus elementum. "
"Etiam a orci. "
"Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Vivamus urna quam, tincidunt at, ultrices vel, feugiat eget, nulla. "
"Maecenas lacus magna, nonummy eu, iaculis sed, consectetuer quis, enim. "
"Praesent a eros. "
"Aliquam nonummy dignissim neque. "
"Nulla enim. "
"Praesent molestie, orci quis tristique volutpat, lacus metus luctus sapien, et facilisis eros neque id sapien. "
"Nunc condimentum dolor vel orci. "
"Integer wisi diam, porttitor sit amet, feugiat in, dapibus in, lectus. "
"Aliquam erat volutpat. "
"Quisque mollis turpis vitae tortor. "
"Mauris turpis mi, pretium ut, ultrices sed, porta in, justo. "
"Suspendisse posuere. "
"Quisque ultricies lacus vitae enim. "
"Donec lacus. "
"Suspendisse potenti. "
"Donec molestie, magna sed euismod dictum, magna magna interdum diam, vitae sagittis leo lorem ac neque. "
"Cras metus. "
"Quisque nunc. "
"Duis consectetuer. "
"Vestibulum gravida sollicitudin urna. "
"Integer volutpat, massa quis ultrices pulvinar, eros purus dignissim nunc, eget rhoncus enim lectus quis tortor. "
"Integer lacinia quam quis erat convallis mattis. "
"Suspendisse iaculis posuere velit. "
"Etiam tellus enim, aliquet nec, laoreet a, molestie non, velit. "
"Quisque lacus velit, eleifend imperdiet, fringilla id, dapibus scelerisque, lectus. "
"Nulla quis lorem. "
"Nulla malesuada neque et dui. "
"Phasellus malesuada ultricies odio. "
"Phasellus vitae ligula. "
"Pellentesque feugiat arcu at erat. "
"Vivamus ut eros ut lorem pulvinar iaculis. "
"Proin lobortis ipsum id nunc. "
"Curabitur vel massa. "
"Suspendisse nulla ipsum, malesuada vel, posuere eget, mollis at, risus. "
"Vestibulum sed diam id est dapibus ultrices. "
"Proin tempus, eros a scelerisque vestibulum, ipsum arcu aliquam mi, ut feugiat libero odio in nisl. "
"Quisque et massa a mauris luctus congue. "
"Ut id eros. "
"Fusce ante eros, pharetra non, molestie tristique, bibendum sit amet, wisi. "
"Phasellus rutrum, dolor et semper elementum, eros ante malesuada massa, sed sollicitudin lectus velit et massa. "
"In auctor. "
"Aliquam erat volutpat. "
"Etiam risus leo, vulputate suscipit, sollicitudin et, sodales eget, nisl. "
"Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Curabitur lobortis, libero ac laoreet mollis, ligula leo porta wisi, ut euismod felis ligula id elit. "
"Vivamus malesuada nulla eu enim. "
"Donec accumsan faucibus orci. "
"Nulla lacinia ante. "
"Praesent at nibh. "
"Mauris porta dignissim wisi. "
"Ut lacinia tortor nec nunc. "
"Phasellus et augue. "
"Integer rhoncus, libero a pellentesque rhoncus, tortor sapien lobortis pede, eget condimentum sapien risus vitae elit. "
"Suspendisse sed turpis ut dolor placerat dignissim. "
"Quisque quis leo. "
"Cras ultrices. "
"Maecenas hendrerit auctor tortor. "
"Etiam sit amet arcu. ";
