inflate_env = Environment ()
# TODO: add the option to build with Quicktime

# Import the C flags set in the SConstruct file
Import ('cflags')
Import ('cxxflags')
Import ('defines')
Import ('extra_includes')
inflate_env.Append (CCFLAGS = cflags)
inflate_env.Append (CXXFLAGS = cxxflags)
inflate_env.Append (CPPDEFINES = defines)

source_files = ['intern/BLO_inflate.c']

inflate_env.Append (CPPPATH = ['.',
                               '../../kernel/gen_messaging',
                               '../readstreamglue'])

inflate_env.Append (CPPPATH = extra_includes)
inflate_env.Library (target='#/lib/blender_inflate', source=source_files)
