Import ('extra_includes')
Import ('user_options_dict')
Import ('library_env')

inflate_env = library_env.Copy ()

source_files = ['intern/BLO_inflate.c']

inflate_env.Append (CPPPATH = ['.',
                               '../../kernel/gen_messaging',
                               '../readstreamglue'])

inflate_env.Append (CPPPATH = user_options_dict['Z_INCLUDE'])
inflate_env.Append (CPPPATH = extra_includes)
inflate_env.Library (target='#'+user_options_dict['BUILD_DIR']+'/lib/blender_inflate', source=source_files)
