#!/usr/bin/python

Import('env')

defs = []
sources = env.Glob('*.cpp')

incs = '. .. ../svm ../../render ../../util ../../device'

incs += ' ' + env['BF_OIIO_INC']
incs += ' ' + env['BF_BOOST_INC']
incs += ' ' + env['BF_OSL_INC']
incs += ' ' + env['BF_OPENEXR_INC']

defs.append('CCL_NAMESPACE_BEGIN=namespace ccl {')
defs.append('CCL_NAMESPACE_END=}')
defs.append('WITH_OSL')

cxxflags = env['CXXFLAGS']
if env['OURPLATFORM'] in ('win32-vc', 'win64-vc'):
    cxxflags = "/EHsc -DBOOST_NO_RTTI -DBOOST_NO_TYPEID"
    incs += ' ' + env['BF_PTHREADS_INC']
else:
    cxxflags = "-fno-rtti -DBOOST_NO_RTTI -DBOOST_NO_TYPEID"

env.BlenderLib ('cycles_kernel_osl', sources, Split(incs), defs, libtype=['intern'], priority=[10], cxx_compileflags=Split(cxxflags))
