#!/usr/bin/python

Import('env')

defs = []
incs = []
cxxflags = Split(env['CXXFLAGS'])

sources = env.Glob('*.cpp')

incs.extend('. .. ../svm ../../render ../../util ../../device'.split())
incs.append(env['BF_OIIO_INC'])
incs.append(env['BF_BOOST_INC'])
incs.append(env['BF_OSL_INC'])
incs.append(env['BF_OPENEXR_INC'].split())

defs.append('CCL_NAMESPACE_BEGIN=namespace ccl {')
defs.append('CCL_NAMESPACE_END=}')
defs.append('WITH_OSL')

if env['OURPLATFORM'] in ('win32-vc', 'win64-vc'):
    cxxflags.append('-DBOOST_NO_RTTI -DBOOST_NO_TYPEID'.split())
    incs.append(env['BF_PTHREADS_INC'])
else:
    cxxflags.append('-fno-rtti -DBOOST_NO_RTTI -DBOOST_NO_TYPEID'.split())

env.BlenderLib ('cycles_kernel_osl', sources, incs, defs, libtype=['intern'], priority=[10], cxx_compileflags=cxxflags)
