#!/usr/bin/python
Import ('env')

sources = env.Glob('intern/*.cpp')
incs = '.'

defs = []

if env['WITH_BF_CXX_GUARDEDALLOC']:
    defs.append('WITH_CXX_GUARDEDALLOC')
    incs += ' #intern/guardedalloc'

env.BlenderLib ('bf_intern_string', sources, Split(incs), defs, libtype=['intern','player'], priority = [50,10] )
