#!/usr/bin/python
Import ('env')

sources = env.Glob('intern/*.c') + env.Glob('superlu/*.c')

incs = 'extern superlu'

if (env['OURPLATFORM'] == 'win32-mingw'):
    env.BlenderLib ('blender_ONL', sources, Split(incs), [], libtype=['core','intern','player'], priority=[1,80,22] )
else:
    env.BlenderLib ('blender_ONL', sources, Split(incs), [], libtype=['core','player'], priority=[55,22] )

