#!/usr/bin/python
Import ('env')

sources = env.Glob('intern/*.c') + env.Glob('superlu/*.c')

incs = 'extern superlu'

if (env['OURPLATFORM'] == 'win32-mingw'):
    env.BlenderLib ('bf_intern_opennl', sources, Split(incs), [], libtype=['core','intern'], priority=[1,80] )
else:
    env.BlenderLib ('bf_intern_opennl', sources, Split(incs), [], libtype=['core'], priority=[55] )

