deflate_env = Environment()

# Import the C flags set in the SConstruct file
Import ('cflags')
Import ('cxxflags')
Import ('defines')
Import ('extra_includes')
Import ('user_options_dict')
deflate_env.Append (CCFLAGS = cflags)
deflate_env.Append (CXXFLAGS = cxxflags)
deflate_env.Append (CPPDEFINES = defines)

source_files = ['intern/BLO_deflate.c']

deflate_env.Append (CPPPATH = ['.',
                               '../../kernel/gen_messaging',
                               '../writestreamglue',
                               '../readstreamglue',
                               '../inflate'])

deflate_env.Append (CPPPATH=user_options_dict['Z_INCLUDE'])
deflate_env.Append (CPPPATH=extra_includes)
deflate_env.Library (target='#'+user_options_dict['BUILD_DIR']+'/lib/blender_deflate', source=source_files)
