#!/usr/bin/python
Import ('env')

source_files = ['dds_api.cpp', 'DirectDrawSurface.cpp', 'Stream.cpp', 'BlockDXT.cpp', 'ColorBlock.cpp', 'Image.cpp', 'FlipDXT.cpp']

incs = [
    '.',
    '..',
    '../..',
    '../../../makesdna',
    '../../../blenkernel',
    '../../../blenlib',
    'intern/include',
    '#/intern/guardedalloc',
    '#/intern/utfconv'
    ]


defs = ['WITH_DDS']

env.BlenderLib ('bf_imbuf_dds', source_files, incs, defs, libtype=['core','player'], priority = [230,190])
