#!/usr/bin/python
Import ('env')

sources = env.Glob('*.c')

incs = '../include ../../blenlib ../../blenkernel ../../makesdna ../../imbuf'
incs += ' ../../windowmanager #/intern/guardedalloc #/extern/glew/include'
incs += ' ../../makesrna'
incs += ' ../../python'

defs = []

if not env['WITH_BF_PYTHON']:
	defs.append('DISABLE_PYTHON')

env.BlenderLib ( 'bf_editors_space_script', sources, Split(incs), defs, libtype=['core'], priority=[90] )
