#!/usr/bin/python
Import ('env')


from optparse import OptionParser
import epydoc
from epydoc.docbuilder import build_doc_index
from epydoc import cli
names = env.Glob("source/gameengine/PyDoc/*.py")
docindex = build_doc_index(names)
optvalues = cli.OPTION_DEFAULTS
optvalues["verbose"] = 1
optvalues["quiet"] = 0
optvalues["include_source_code"] = 0
optvalues["inheritance"] = "included"
optvalues["show_private"] = 0
optvalues["target"] = env["BF_DOCDIR"]+"/BGE_API/"
optvalues["url"] = "http://www.blender.org"
optvalues["top"] = "Game Engine API"
optvalues["name"] = "Blender"
optvalues["noprivate"] = 1
optvalues["noframes"] = 1
optvalues["names"] = names
optparser = OptionParser()
optparser.set_defaults(**optvalues)
(options, args) = optparser.parse_args([])
print "Writing Game Engine epydocs to \"%s\"" % optvalues["target"]
cli.write_html(docindex, options)

