#!/usr/bin/python
Import ('env')

sources = env.Glob('intern/*.cpp')

defs = ''

if env['WITH_BF_OPENMP']:
    defs += ' PARALLEL=1'

incs = env['BF_PNG_INC'] + ' ' + env['BF_ZLIB_INC'] 
incs += ' intern ../../extern/bullet2/src ../memutil ../guardealloc '

if env['WITH_BF_FFTW3']:
    defs += ' FFTW3=1'
    incs += env['BF_FFTW3_INC'] 

env.BlenderLib ('bf_smoke', sources, Split(incs), Split(defs), libtype=['intern'], priority=[40] )
