Import ('user_options_dict')
Import ('library_env')

creator_env = library_env.Copy ()

source_files = ['creator.c']

creator_env.Append (CPPPATH = ['#/intern/guardedalloc',
                               '../blender/blenlib',
                               '../blender/blenkernel',
                               '../blender/include',
                               '../blender/blenloader',
                               '../blender/imbuf',
                               '../blender/renderconverter',
                               '../blender/render/extern/include',
                               '../blender/python',
                               '../blender/makesdna',
                               '../kernel/gen_messaging',
                               '../kernel/gen_system'])
creator_env.Append (CPPPATH = user_options_dict['OPENGL_INCLUDE'])

if user_options_dict['USE_QUICKTIME'] == 1:
    creator_env.Append (CPPDEFINES = ['WITH_QUICKTIME'])

creator_env.Library (target='#'+user_options_dict['BUILD_DIR']+'/lib/blender_creator', source=source_files)
