Import ('user_options_dict')
Import ('library_env')

iksolver_env = library_env.Copy ()

source_files = ['intern/IK_QChain.cpp',
                'intern/IK_QJacobianSolver.cpp',
                'intern/IK_QSegment.cpp',
                'intern/IK_Solver.cpp',
                'intern/MT_ExpMap.cpp']

iksolver_env.Append (CPPPATH = ['intern',
                                '../moto/include',
                                '../memutil'])

iksolver_env.Library (target='#'+user_options_dict['BUILD_DIR']+'/lib/blender_IK', source=source_files)
