#!/usr/bin/python
Import ('env')

sources = env.Glob('intern/*.cpp')

incs = 'intern ../moto/include ../memutil'

env.BlenderLib ('bf_intern_iksolver', sources, Split(incs), [], libtype=['intern','player'], priority=[100,90] )

