#!/usr/bin/python
Import ('env')

sources = env.Glob('intern/*.c')

incs = '. #/intern/guardedalloc ../editors/include ../blenlib ../makesdna'
incs += ' ../render/extern/include #/intern/decimation/extern ../makesrna'
incs += ' ../imbuf ../avi #/intern/elbeem/extern ../nodes'
incs += ' #/intern/iksolver/extern ../blenloader'
incs += ' #/extern/bullet2/src'
incs += ' #/intern/bmfont'
incs += ' #/intern/opennl/extern #/intern/bsp/extern'
incs += ' ../gpu #/extern/glew/include'
incs += ' ../bmesh'

incs += ' ' + env['BF_OPENGL_INC']
incs += ' ' + env['BF_ZLIB_INC']

defs = ''

if not env['WITH_BF_PYTHON']:
	defs += 'DISABLE_PYTHON'
else:
	incs += ' ../python'
	incs += ' ' + env['BF_PYTHON_INC']

if env['WITH_BF_QUICKTIME']:
    incs += ' ../quicktime'

if env['WITH_BF_SDL']:
	incs += ' ' + env['BF_SDL_INC']
else:
	defs += ' DISABLE_SDL'

if env['WITH_BF_INTERNATIONAL']:
	defs += ' WITH_FREETYPE2'
	
if env['WITH_BF_OPENEXR']:
    defs += ' WITH_OPENEXR'

if env['WITH_BF_OPENJPEG']:
    defs += ' WITH_OPENJPEG'

if env['WITH_BF_DDS']:
    defs += ' WITH_DDS'

if env['WITH_BF_FFMPEG']:
    defs += ' WITH_FFMPEG'
    incs += ' ' + env['BF_FFMPEG_INC']

if env['WITH_BF_QUICKTIME']:
    defs += ' WITH_QUICKTIME'
    incs += ' ' + env['BF_QUICKTIME_INC']

if env['WITH_BF_BULLET']:
    defs += ' WITH_BULLET'

if env['BF_NO_ELBEEM']:
    defs += ' DISABLE_ELBEEM'

if env['OURPLATFORM'] in ('win32-vc', 'win32-mingw', 'linuxcross', 'win64-vc'):
    incs += ' ' + env['BF_PTHREADS_INC']

env.BlenderLib ( libname = 'bf_blenkernel', sources = sources, includes = Split(incs), defines = Split(defs), libtype=['core'], priority = [165] )
