#!/usr/bin/python
import sys
Import ('env')


source_files = ['bmfont.cpp',
                'GPC_Canvas.cpp',
                'GPC_Engine.cpp',
                'GPC_KeyboardDevice.cpp',
                'GPC_MouseDevice.cpp',
                'GPC_PolygonMaterial.cpp',
                'GPC_RawImage.cpp',
                'GPC_RawLoadDotBlendArray.cpp',
                'GPC_RawLogoArrays.cpp',
                'GPC_RenderTools.cpp',
                'GPC_System.cpp']

incs = ['.',
        '#intern/string',
        '#intern/ghost',
        '#intern/guardedalloc',
        '#intern/bmfont',
        '#intern/moto/include',
        '#intern/SoundSystem',
        '#source/gameengine/Rasterizer/RAS_OpenGLRasterizer',
        '#source/kernel/gen_system',
        '#source/kernel/gen_messaging',
        '#source/gameengine/Converter',
        '#source/blender/imbuf',
        '#source/gameengine/Ketsji',
        '#source/blender/blenlib',
        '#source/blender/blenkernel',
        '#source/blender',
        '#source/blender/include',
        '#source/blender/makesdna',
        '#source/gameengine/BlenderRoutines',
        '#source/gameengine/Rasterizer',
        '#source/gameengine/GameLogic',
        '#source/gameengine/Expressions',
        '#source/gameengine/Network',
        '#source/gameengine/SceneGraph',
        '#source/gameengine/Physics/common',
        '#source/gameengine/Physics/Sumo',
        '#source/gameengine/Physics/Sumo/Fuzzics/include',
        '#source/gameengine/Network/LoopBackNetwork',
        '#source/gameengine/GamePlayer/ghost',
        '#source/blender/misc',
        '#source/blender/blenloader',
		'#extern/glew/include']
                                
#This is all plugin stuff!
#if sys.platform=='win32':
#   source_files += ['windows/GPW_Canvas.cpp',
#                    'windows/GPW_Engine.cpp',
#                    'windows/GPW_KeyboardDevice.cpp',
#                    'windows/GPW_System.cpp']
#   gp_common_env.Append ( CPPPATH = ['windows'])
#elif sys.platform=='linux2' or sys.platform=='linux-i386':
#   source_files += ['unix/GPU_Canvas.cpp',
#                    'unix/GPU_Engine.cpp',
#                    'unix/GPU_KeyboardDevice.cpp',
#                    'unix/GPU_System.cpp']
#   gp_common_env.Append ( CPPPATH = ['unix'])

incs += Split(env['BF_PYTHON_INC'])
incs += Split(env['BF_SOLID_INC'])
incs += Split(env['BF_PNG_INC'])
incs += Split(env['BF_ZLIB_INC'])

cflags=[]
if env['OURPLATFORM']=='win32-vc':
    cflags = ['/GR']

env.BlenderLib (libname='gp_common', sources=source_files, includes=incs, defines = [], libtype='player', priority=5, compileflags=cflags)
