import bpy
op = bpy.context.active_operator

op.location = (0.0, 0.0, 0.0)
op.view_align = False
op.rotation = (0.0, 0.0, 0.0)
op.options_plus = False
op.absolute_location = False
op.use_colors = False
op.colorSet = '1'
op.random_colors = False
op.saturation = 0.75
op.geo_surface = True
op.geo_bDepth = 0.029999999329447746
op.geo_bRes = 3
op.geo_extrude = 0.0
op.geo_offset = 0.0
op.torus_p = 13
op.torus_q = 8
op.flip_p = False
op.flip_q = False
op.multiple_links = True
op.torus_u = 1
op.torus_v = 1
op.torus_rP = 0.0
op.torus_sP = 0.0
op.mode = 'MAJOR_MINOR'
op.torus_R = 0.0
op.torus_r = 1.0
op.torus_iR = 0.75
op.torus_eR = 1.25
op.torus_s = 1.0
op.torus_h = 1.0
op.torus_res = 767
op.segment_res = 12
op.outputType = 'BEZIER'
op.handleType = 'AUTOMATIC'
op.adaptive_resolution = True
