Import ('extra_includes')
Import ('user_options_dict')
Import ('library_env')

python_env = library_env.Copy ()

source_files = ['BPY_interface.c',
                'BPY_menus.c',
                'api2_2x/Blender.c',
                'api2_2x/Sys.c',
                'api2_2x/Registry.c',
                'api2_2x/Scene.c',
                'api2_2x/Types.c',
                'api2_2x/Object.c',
                'api2_2x/NMesh.c',
                'api2_2x/Material.c',
                'api2_2x/Camera.c',
                'api2_2x/World.c',
                'api2_2x/Lamp.c',
                'api2_2x/Lattice.c',
                'api2_2x/Curve.c',
                'api2_2x/Armature.c',
                'api2_2x/Bone.c',
                'api2_2x/Ipo.c',
                'api2_2x/Ipocurve.c',
                'api2_2x/BezTriple.c',
                'api2_2x/Metaball.c',
                'api2_2x/Effect.c',
                'api2_2x/Particle.c',
                'api2_2x/Wave.c',
                'api2_2x/Build.c',
                'api2_2x/Image.c',
                'api2_2x/Window.c',
                'api2_2x/Draw.c',
                'api2_2x/BGL.c',
                'api2_2x/Text.c',
                'api2_2x/Texture.c',
                'api2_2x/MTex.c',
                'api2_2x/Noise.c',
                'api2_2x/vector.c',
                'api2_2x/constant.c',
                'api2_2x/matrix.c',
                'api2_2x/euler.c',
                'api2_2x/quat.c',
                'api2_2x/Mathutils.c',
                'api2_2x/rgbTuple.c',
                'api2_2x/gen_utils.c',
                'api2_2x/sceneRender.c',
                'api2_2x/EXPP_interface.c'
		'api2_2x/Noise.c']

python_env.Append (CPPPATH = ['api2_2x',
                              '../blenkernel',
                              '../blenlib',
                              '../render/extern/include',
                              '../makesdna',
                              '#/intern/guardedalloc',
                              '#/intern/bmfont',
                              '../imbuf',
                              '../include'])

python_env.Append (CPPPATH = user_options_dict['PYTHON_INCLUDE'])
python_env.Append (CPPPATH = user_options_dict['OPENGL_INCLUDE'])
python_env.Append (CPPPATH = extra_includes)
python_env.Library (target='#'+user_options_dict['BUILD_DIR']+'/lib/blender_python', source=source_files)
