#!/usr/bin/python
Import ('env')

sources = 'stubs.c'

incs = '#/source/blender/makesdna'
incs += ' #/source/blender/makesrna'

defs = ''
if env['WITH_BF_INTERNATIONAL']:
    defs += 'WITH_FREETYPE2'

env.BlenderLib ('blenkernel_blc', sources = Split(sources), includes=Split(incs), defines=Split(defs), libtype=['player'],priority=[220] )
