#!/usr/bin/python
import sys
Import ('user_options_dict')
Import ('library_env')

phy_bullet_env = library_env.Copy ()

source_files = ['CcdPhysicsEnvironment.cpp',
                'CcdPhysicsController.cpp'
               ]

phy_bullet_env.Append (CPPPATH=['.', 
				'../common'])

phy_bullet_env.Append (CPPPATH = user_options_dict['BULLET_INCLUDE'])


if sys.platform=='win32':
	phy_bullet_env.Append (CXXFLAGS = ['/GR'])
	phy_bullet_env.Append (CCFLAGS =['/O2'])

phy_bullet_env.Library (target='#'+user_options_dict['BUILD_DIR']+'/lib/PHY_Bullet', source=source_files)
