#!/usr/bin/python
Import ('env')

sources = 'CcdPhysicsEnvironment.cpp CcdPhysicsController.cpp CcdGraphicController.cpp'

incs = '. ../common'
incs += ' #source/kernel/gen_system'
incs += ' #intern/string'
incs += ' #intern/moto/include'
incs += ' #extern/glew/include'
incs += ' #source/gameengine/Rasterizer'
incs += ' #source/gameengine/Ketsji'
incs += ' #source/gameengine/Expressions'
incs += ' #source/gameengine/GameLogic'
incs += ' #source/gameengine/SceneGraph'
incs += ' #source/blender/makesdna'
incs += ' #source/blender/blenkernel'
incs += ' #source/blender/blenlib'
incs += ' #intern/guardedalloc'

incs += ' ' + env['BF_BULLET_INC']
incs += ' ' + env['BF_PYTHON_INC']

env.BlenderLib ( 'bf_bullet', Split(sources), Split(incs), [], libtype=['core','player'], priority=[350,50], cxx_compileflags=env['BGE_CXXFLAGS'])
