#!/usr/bin/python
Import ('env')

sources = 'CcdPhysicsEnvironment.cpp CcdPhysicsController.cpp CcdGraphicController.cpp'

incs = '. ../common'
incs += ' #intern/string'
incs += ' #intern/moto/include'
incs += ' #extern/glew/include'
incs += ' #source/gameengine/Rasterizer'
incs += ' #source/gameengine/Ketsji'
incs += ' #source/gameengine/Expressions'
incs += ' #source/gameengine/GameLogic'
incs += ' #source/gameengine/SceneGraph'
incs += ' #source/blender/makesdna'
incs += ' #source/blender/blenkernel'
incs += ' #source/blender/blenlib'
incs += ' #intern/guardedalloc'
incs += ' #intern/container'

incs += ' ' + env['BF_BULLET_INC']

defs = []

if env['WITH_BF_PYTHON']:
    incs += ' ' + env['BF_PYTHON_INC']
    defs.append('WITH_PYTHON')

if env['WITH_BF_CXX_GUARDEDALLOC']:
    defs.append('WITH_CXX_GUARDEDALLOC')

if env['WITH_BF_BULLET']:
    defs.append('USE_BULLET')

env.BlenderLib ( 'ge_phys_bullet', Split(sources), Split(incs), defs, libtype=['core','player'], priority=[350,50], cxx_compileflags=env['BGE_CXXFLAGS'])
