# -*- mode: gnumakefile; tab-width: 8; indent-tabs-mode: t; -*-
# vim: tabstop=8
#
# $Id$
#
# ***** BEGIN GPL LICENSE BLOCK *****
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version. 
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
# The Original Code is Copyright (C) Blender Foundation.
# All rights reserved.
#
# The Original Code is: all of this file.
#
# Contributor(s): none yet.
#
# ***** END GPL LICENSE BLOCK *****
#
# Bounces make to subdirectories.

SOURCEDIR = source/blender/editors
DIRS = armature \
  mesh \
  animation \
  object \
  sculpt_paint \
  datafiles \
  transform \
  screen \
  curve \
  metaball \
  gpencil \
  physics \
  preview \
  uvedit \
  space_outliner \
  space_time \
  space_view3d \
  interface \
  util \
  space_api \
  space_console \
  space_graph \
  space_image \
  space_node \
  space_buttons \
  space_info \
  space_file \
  space_sound \
  space_action \
  space_nla \
  space_script \
  space_text \
  space_sequencer \
  space_logic \
  space_userpref \
  sound

include nan_subdirs.mk
