#!/usr/bin/python
Import ('env')


SConscript(['datafiles/SConscript',
			'space_api/SConscript',
			'util/SConscript',
			'interface/SConscript',
			'mesh/SConscript',
			'object/SConscript',
			'space_outliner/SConscript',
			'space_time/SConscript',
			'space_view3d/SConscript',
			'space_ipo/SConscript',
			'transform/SConscript',
			'screen/SConscript'])
