phy_dummy_env = Environment()

# Import the C flags set in the SConstruct file
Import ('cflags')
Import ('cxxflags')
Import ('defines')
phy_dummy_env.Append (CCFLAGS = cflags)
phy_dummy_env.Append (CXXFLAGS = cxxflags)
phy_dummy_env.Append (CPPDEFINES = defines)

source_files = ['DummyPhysicsEnvironment.cpp']

phy_dummy_env.Append (CPPPATH = ['.',
                                 '../common'
                                ])

phy_dummy_env.Library (target='#/lib/PHY_Dummy', source=source_files)
