Import ('user_options_dict')
Import ('library_env')

phy_dummy_env = library_env.Copy ()

source_files = ['DummyPhysicsEnvironment.cpp']

phy_dummy_env.Append (CPPPATH = ['.',
                                 '../common'
                                ])

phy_dummy_env.Library (target='#'+user_options_dict['BUILD_DIR']+'/lib/PHY_Dummy', source=source_files)
