kx_blenderhook_env = Environment()

# Import the C flags set in the SConstruct file
Import ('cflags')
Import ('cxxflags')
Import ('defines')
Import ('python_include')
kx_blenderhook_env.Append (CCFLAGS = cflags)
kx_blenderhook_env.Append (CXXFLAGS = cxxflags)
kx_blenderhook_env.Append (CPPDEFINES = defines)

source_files = ['KX_BlenderSystem.cpp',
                'KX_BlenderRenderTools.cpp',
                'KX_BlenderPolyMaterial.cpp',
                'KX_BlenderMouseDevice.cpp',
                'KX_BlenderKeyboardDevice.cpp',
                'KX_BlenderInputDevice.cpp',
                'KX_BlenderGL.cpp',
                'KX_BlenderCanvas.cpp',
                'BL_KetsjiEmbedStart.cpp']

kx_blenderhook_env.Append (CPPPATH=['.',
                                    '#source/kernel/gen_system',
                                    '#intern/string',
                                    '#intern/guardedalloc',
                                    '#source/gameengine/Rasterizer/RAS_OpenGLRasterizer',
                                    python_include,
                                    '#intern/bmfont',
                                    '#source/gameengine/Converter',
                                    '#source/blender/imbuf',
                                    '#intern/moto/include',
                                    '#source/gameengine/Ketsji',
                                    '#source/blender/blenlib',
                                    '#source/blender/blenkernel',
                                    '#source/blender',
                                    '#source/blender/include',
                                    '#source/blender/makesdna',
                                    '#source/gameengine/Rasterizer',
                                    '#source/gameengine/GameLogic',
                                    '#source/gameengine/Expressions',
                                    '#source/gameengine/Network',
                                    '#source/gameengine/SceneGraph',
                                    '#source/gameengine/Physics/Sumo/include',
                                    '#source/gameengine/Physics/Sumo/Fuzzics/include',
                                    '#source/gameengine/Network/LoopBackNetwork',
                                    '#intern/SoundSystem',
                                    '#source/blender/misc',
                                    '#source/blender/blenloader',
                                    '#../lib/windows/solid/include',
                                    ])

kx_blenderhook_env.Library (target='#/lib/KX_blenderhook', source=source_files)
