#!/usr/bin/python
Import ('user_options_dict')
Import ('library_env')

blenkernel_blc_env = library_env.Copy ()

source_files = ['stubs.c'
                ]
blenkernel_blc_env.Append (CPPPATH = ['.',
                                  '..',
                                  '../../render/extern/include',
                                  '#/intern/iksolver/extern',
                                  '../../blenlib',
                                  '../../include',
                                  '../../makesdna'])
"""
,
                                  '#/intern/guardedalloc',
                                  '../python',
                                  '../imbuf',
                                  '../avi',
                                  '../blenloader']
"""
if user_options_dict['USE_INTERNATIONAL'] == 1:
    blenkernel_blc_env.Append (CPPDEFINES = 'WITH_FREETYPE2')

blenkernel_blc_env.Library (target='#'+user_options_dict['BUILD_DIR']+'/lib/blender_blenkernel_blc', source=source_files)
