#!/usr/bin/python
Import ('env')

sources = 'stubs.c'

incs = '. .. ../../render/extern/include'
incs += ' #/intern/iksolver/extern ../../blenlib'
incs += ' ../../include ../../makesdna'

defs = ''
if env['WITH_BF_INTERNATIONAL']:
    defs += 'WITH_FREETYPE2'

env.BlenderLib ('blenkernel_blc', sources = Split(sources), includes=Split(incs), defines=Split(defs), libtype='player',priority=225 )
