#!/usr/bin/env python
#
# ***** BEGIN GPL LICENSE BLOCK *****
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
#
# The Original Code is Copyright (C) 2006, Blender Foundation
# All rights reserved.
#
# The Original Code is: all of this file.
#
# Contributor(s): Nathan Letwory.
#
# ***** END GPL LICENSE BLOCK *****

Import ('env')

sources = env.Glob('intern/*.cpp')

incs = 'intern ../container ../moto/include ../memutil ../guardedalloc  ../../extern/carve/include'

defs = []

if env['WITH_BF_BOOST']:
    isMINGW = env['OURPLATFORM'] in ('win32-mingw', 'win64-mingw')

    if env['OURPLATFORM'] not in ('win32-vc', 'win64-vc') and not isMINGW:
        # Boost is setting as preferred collections library in the Carve code when using MSVC compiler
        defs.append('HAVE_BOOST_UNORDERED_COLLECTIONS')

    if not isMINGW:
        defs.append('CARVE_SYSTEM_BOOST')

    incs +=  ' ' + env['BF_BOOST_INC']

env.BlenderLib ('bf_intern_bsp', sources, Split(incs), defs, libtype=['core','player'], priority=[200,100] )

