#!/usr/bin/python
Import ('env')

sources = env.Glob('intern/*.cpp')

incs = 'intern ../container ../moto/include ../memutil'

env.BlenderLib ('bf_intern_bsp', sources, Split(incs), [], libtype=['core','player'], priority=[200,100] )

