#!/usr/bin/python
Import ('env')

sources = env.Glob('*.c')

incs = '../include ../../blenlib ../../blenkernel ../../blenfont ../../makesdna ../../imbuf'
incs += ' ../../blenloader ../../windowmanager ../../python ../../makesrna'
incs += ' ../../render/extern/include'
incs += ' #/intern/guardedalloc #/extern/glew/include'

defs = ''

if not env['WITH_BF_PYTHON']:
    defs += 'DISABLE_PYTHON'
if env['WITH_BF_OPENEXR']:
	defs += ' WITH_OPENEXR'

if env['OURPLATFORM'] == 'linux2':
	cflags='-pthread'
    	incs += ' ../../../extern/binreloc/include'

if env['OURPLATFORM'] in ('win32-vc', 'win32-mingw', 'linuxcross', 'win64-vc'):
	incs += ' ' + env['BF_PTHREADS_INC']

env.BlenderLib ( 'bf_editors_screen', sources, Split(incs), Split(defs), libtype=['core'], priority=[105] )
