#!/usr/bin/python
Import ('env')

sources = env.Glob('*.c')

incs = '../include ../../blenlib ../../blenkernel ../../makesdna ../../imbuf'
incs += ' ../../blenloader ../../windowmanager ../../python ../../makesrna'
incs += ' #/intern/guardedalloc #/extern/glew/include'

defs = ''

if not env['WITH_BF_PYTHON']:
    defs += 'DISABLE_PYTHON'

env.BlenderLib ( 'bf_editors_screen', sources, Split(incs), Split(defs), libtype=['core','intern'], priority=[30, 35] )
