Import ('user_options_dict')
Import ('library_env')

ras_openglrasterizer_env = library_env.Copy ()

source_files = ['RAS_GLExtensionManager.cpp',
                'RAS_OpenGLRasterizer.cpp',
                'RAS_VAOpenGLRasterizer.cpp']

ras_openglrasterizer_env.Append (CPPPATH=['.',
                                          '#source/kernel/gen_system',
                                          '#intern/string',
                                          '#intern/moto/include',
                                          '#source/gameengine/Rasterizer'
                                         ])

ras_openglrasterizer_env.Library (target='#'+user_options_dict['BUILD_DIR']+'/lib/RAS_OpenGLRasterizer', source=source_files)
