#!/usr/bin/python
Import ('env')

if env['WITH_BF_GLEXT'] == 1:
        env['CPPFLAGS'].append('-DWITH_GLEXT')

sources = env.Glob('*.cpp')

incs = '. #source/kernel/gen_system #intern/string #intern/moto/include #source/gameengine/Rasterizer #source/gameengine/BlenderRoutines '
incs += ' #extern/glew/include ' + env['BF_OPENGL_INC']

env.BlenderLib ( 'bf_oglrasterizer', Split(sources), Split(incs), [], libtype=['game','player'], priority=[40, 120] )
