#!/usr/bin/python
Import ('env')

sources = env.Glob('*.c')

incs = '../include ../../blenfont ../../blenlib ../../blenkernel ../../makesdna ../../imbuf'
incs += ' ../../windowmanager #/intern/guardedalloc #/extern/glew/include'
incs += ' ../../render/extern/include'
incs += ' ../../gpu ../../makesrna ../../blenloader ../../bmesh'

defs = []

if env['WITH_BF_INTERNATIONAL']:
    defs.append('WITH_INTERNATIONAL')

env.BlenderLib ( 'bf_editors_transform', sources, Split(incs), defs, libtype=['core'], priority=[40] )
