#!/usr/bin/python
Import ('env')

sources = env.Glob('intern/*.c')

incs = '../blenlib ../blenkernel ../makesdna ../include'
incs += ' #/extern/glew/include #intern/guardedalloc ../imbuf .'

incs += ' ' + env['BF_OPENGL_INC']

env.BlenderLib ( 'bf_gpu', sources, Split(incs), [], libtype=['core', 'player'], priority=[65, 20] )
