#!/usr/bin/python
Import ('env')

sources = env.Glob('intern/*.c')
sources += env.Glob('shaders/*.c')

defs = [ 'GLEW_STATIC' ]

incs = '../blenlib ../blenkernel ../makesdna ../makesrna ../include ../blenloader ../nodes ../nodes/intern'
incs += ' #/extern/glew/include #intern/guardedalloc #intern/smoke/extern ../imbuf .'

if env['OURPLATFORM'] in ('win32-vc', 'win32-mingw', 'linuxcross', 'win64-vc', 'win64-mingw'):
    incs += ' ' + env['BF_PTHREADS_INC']

incs += ' ' + env['BF_OPENGL_INC']

if env['WITH_BF_SMOKE']:
    defs.append('WITH_SMOKE')

if env['WITH_BF_DDS']:
	defs.append('WITH_DDS')

# generated data files
import os
sources.extend((
	os.path.join(env['DATA_SOURCES'], "gpu_shader_material.glsl.c"),
	os.path.join(env['DATA_SOURCES'], "gpu_shader_vertex.glsl.c"),
	os.path.join(env['DATA_SOURCES'], "gpu_shader_sep_gaussian_blur_frag.glsl.c"),
	os.path.join(env['DATA_SOURCES'], "gpu_shader_sep_gaussian_blur_vert.glsl.c"),
	os.path.join(env['DATA_SOURCES'], "gpu_shader_vsm_store_frag.glsl.c"),
	os.path.join(env['DATA_SOURCES'], "gpu_shader_vsm_store_vert.glsl.c"),
	))

env.BlenderLib ( 'bf_gpu', sources, Split(incs), defines = defs, libtype=['core','player'], priority=[160,110] )
