# SPDX-FileCopyrightText: 2002-2026 Blender Authors
#
# SPDX-License-Identifier: GPL-2.0-or-later

set(JOLT_EXTRA_ARGS
  -DDEBUG_RENDERER_IN_DEBUG_AND_RELEASE=OFF
  -DJPH_BUILD_SHARED_LIBS=ON
  -DJPH_USE_DX12=OFF
  -DJPH_USE_MTL=OFF
  -DJPH_USE_VK=OFF

  -DTARGET_HELLO_WORLD=OFF
  -DTARGET_PERFORMANCE_TEST=OFF
  -DTARGET_SAMPLES=OFF
  -DTARGET_UNIT_TESTS=OFF
  -DTARGET_VIEWER=OFF

  -DCROSS_PLATFORM_DETERMINISTIC=ON

  # TODO check AVX and SSE toggles
)


ExternalProject_Add(external_jolt
  URL file://${PACKAGE_DIR}/${JOLT_FILE}
  DOWNLOAD_DIR ${DOWNLOAD_DIR}
  URL_HASH ${JOLT_HASH_TYPE}=${JOLT_HASH}
  PREFIX ${BUILD_DIR}/jolt
  CMAKE_GENERATOR ${PLATFORM_ALT_GENERATOR}
  SOURCE_SUBDIR Build

  CMAKE_ARGS
    -DCMAKE_INSTALL_PREFIX=${LIBDIR}/jolt
    ${DEFAULT_CMAKE_FLAGS}
    ${JOLT_EXTRA_ARGS}

  INSTALL_DIR ${LIBDIR}/jolt
)
