# SPDX-FileCopyrightText: 2026 Blender Authors
#
# SPDX-License-Identifier: GPL-2.0-or-later

set(RAPIDJSON_EXTRA_ARGS
  -DRAPIDJSON_BUILD_DOC=OFF
  -DRAPIDJSON_BUILD_EXAMPLES=OFF
  -DRAPIDJSON_BUILD_TESTS=OFF
)

ExternalProject_Add(external_rapidjson
  URL file://${PACKAGE_DIR}/${RAPIDJSON_FILE}
  DOWNLOAD_DIR ${DOWNLOAD_DIR}
  URL_HASH ${RAPIDJSON_HASH_TYPE}=${RAPIDJSON_HASH}
  PREFIX ${BUILD_DIR}/rapidjson
  CMAKE_GENERATOR ${PLATFORM_ALT_GENERATOR}

  CMAKE_ARGS
    -DCMAKE_INSTALL_PREFIX=${LIBDIR}/rapidjson
    ${DEFAULT_CMAKE_FLAGS}
    ${RAPIDJSON_EXTRA_ARGS}

  INSTALL_DIR ${LIBDIR}/rapidjson
)
