#!/usr/bin/env python
#
# ***** BEGIN GPL LICENSE BLOCK *****
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
#
# The Original Code is Copyright (C) 2006, Blender Foundation
# All rights reserved.
#
# The Original Code is: all of this file.
#
# Contributor(s): Nathan Letwory.
#
# ***** END GPL LICENSE BLOCK *****

Import ('env')

sources = env.Glob('*.cpp') + env.Glob('Joystick/*.cpp')

incs = [
    '.',
    '#intern/container',
    '#intern/ghost',
    '#/intern/string',
    '#/intern/moto/include',
    '#/source/blender/blenlib',
    '#/source/gameengine/Expressions',
    '#/source/gameengine/Rasterizer',
    '#/source/gameengine/SceneGraph',
    ]
incs = ' '.join(incs)

defs = []

if env['WITH_BF_SDL']:
    defs.append('WITH_SDL')
    incs += ' ' + env['BF_SDL_INC']

if env['WITH_BF_PYTHON']:
    incs += ' ' + env['BF_PYTHON_INC']
    defs.append('WITH_PYTHON')

if env['OURPLATFORM'] in ('win32-vc', 'win64-vc'):
    if env['BF_DEBUG']:
        defs.append('_DEBUG')

if env['WITH_BF_CXX_GUARDEDALLOC']:
    defs.append('WITH_CXX_GUARDEDALLOC')
    incs += ' #/intern/guardedalloc'

env.BlenderLib ( 'ge_logic', sources, Split(incs), defs, libtype=['core','player'], priority=[330,65], cxx_compileflags=env['BGE_CXXFLAGS'])
