#!/usr/bin/python
Import ('env')

sources = env.Glob('*.cpp') + env.Glob('Joystick/*.cpp')

incs = '. #/source/kernel/gen_system #/intern/string'
incs += ' #/source/gameengine/Expressions #/intern/moto/include'
incs += ' #/source/gameengine/Rasterizer #/source/gameengine/SceneGraph'

incs += ' ' + env['BF_PYTHON_INC']


defs = ''

if env['WITH_BF_SDL']:
	incs += ' ' + env['BF_SDL_INC']
else:
	defs += ' DISABLE_SDL'

cxxflags = []
if env['OURPLATFORM']=='win32-vc':
	cxxflags.append ('/GR')
	cxxflags.append ('/O2')

env.BlenderLib ( 'bf_logic', sources, Split(incs), Split(defs), libtype=['core','player'], priority=[330, 100], cxx_compileflags=cxxflags )
