#!/usr/bin/python
Import ('env')

sources = env.Glob('intern/*.c')

incs = '. ./intern'
incs += ' #/intern/guardedalloc #/intern/decimation/extern #/intern/bsp/extern #/intern/elbeem/extern #/extern/glew/include'
incs += ' ../render/extern/include ../blenloader ../bmesh'
incs += ' ../include ../blenlib ../makesdna ../makesrna ../blenkernel ../blenkernel/intern'
incs += ' ../gpu'

incs += ' ' + env['BF_ZLIB_INC']

defs = []

# could be made optional
defs += ['WITH_MOD_BOOLEAN']
defs += ['WITH_MOD_DECIMATE']

if env['BF_NO_ELBEEM']:
    defs.append('DISABLE_ELBEEM')

if env['WITH_BF_GAMEENGINE']:
    incs += ' #/extern/recastnavigation'
    defs.append('WITH_GAMEENGINE')

env.BlenderLib ( libname = 'bf_modifiers', sources = sources,
                 includes = Split(incs), defines=defs,
                 libtype=['core','player'], priority = [80, 40] )
