#!/usr/bin/python

Import ('env')

sources = env.Glob('dummy/*.cpp') + env.Glob('intern/*.cpp')

incs = '. intern ../moto/include ../string dummy openal sdl'
defs = ''
if env['WITH_BF_OPENAL']:
	sources += env.Glob('openal/*.cpp') + env.Glob('sdl/*.cpp')
	incs += ' ' + env['BF_OPENAL_INC']
	incs += ' ' + env['BF_SDL_INC']
	defs = 'USE_OPENAL'
else:
	defs = 'NO_SOUND'

if not env['WITH_BF_SDL']:
	defs += ' DISABLE_SDL'

env.BlenderLib ('bf_soundsystem', sources, Split(incs), Split(defs), libtype=['core','player'], priority = [20,140] )
