#!/usr/bin/python

Import ('user_options_dict')
Import ('library_env')

sg_scenegraph_env = library_env.Copy ()

source_files = ['SG_BBox.cpp',
                'SG_Controller.cpp',
                'SG_IObject.cpp',
                'SG_Node.cpp',
                'SG_Spatial.cpp',
                'SG_Tree.cpp']

sg_scenegraph_env.Append (CPPPATH=['.',
                                   '#intern/moto/include'
                                  ])

sg_scenegraph_env.Library (target='#'+user_options_dict['BUILD_DIR']+'/lib/SG_SceneGraph', source=source_files)
