#!/usr/bin/python
Import ('env')

sources = env.Glob('intern/*.cpp')

incs = 'include'

env.BlenderLib ('blender_MT', sources, Split(incs), [], libtype=['intern','game','game2'], priority = [15, 55,100] )
