Import ('user_options_dict')
Import ('library_env')

moto_env = library_env.Copy ()

source_files = ['intern/MT_CmMatrix4x4.cpp',
                'intern/MT_Matrix3x3.cpp',
                'intern/MT_Matrix4x4.cpp',
                'intern/MT_Plane3.cpp',
                'intern/MT_Point3.cpp',
                'intern/MT_Quaternion.cpp',
                'intern/MT_Transform.cpp',
                'intern/MT_Vector2.cpp',
                'intern/MT_Vector3.cpp',
                'intern/MT_Vector4.cpp',
                'intern/MT_random.cpp']

moto_env.Append (CPPPATH = ['include'])

moto_env.Library (target='#'+user_options_dict['BUILD_DIR']+'/lib/blender_MT', source=source_files)
