#!/usr/bin/python
Import ('env')

sumoenv = env.Copy()
sources = ['SumoPHYCallbackBridge.cpp',
                'SumoPhysicsController.cpp',
                'SumoPhysicsEnvironment.cpp',
                'Fuzzics/src/SM_FhObject.cpp',
                'Fuzzics/src/SM_Object.cpp',
                'Fuzzics/src/SM_Scene.cpp',
                'Fuzzics/src/SM_MotionState.cpp'
               ]

incs =['.',
	'../common',
	'Fuzzics/include',
	'#/intern/moto/include'
	]
incs += [sumoenv['BF_SOLID_INC']]

if sumoenv['PLATFORM']=='win32':
	sumoenv.Append (CXXFLAGS = ['/GR'])
	sumoenv.Append ( CCFLAGS =['/O1'])

#env.Library (target='#'+user_options_dict['BUILD_DIR']+'/lib/PHY_Sumo', source=source_files)
env.BlenderLib ( 'PHY_Sumo', sources, incs, [], libtype='game2', priority=30 )
