import sys
Import ('user_options_dict')
Import ('library_env')

phy_sumo_env = library_env.Copy ()

source_files = ['SumoPhysicsController.cpp',
                'SumoPhysicsEnvironment.cpp',
                'Fuzzics/src/SM_FhObject.cpp',
                'Fuzzics/src/SM_Object.cpp',
                'Fuzzics/src/SM_Scene.cpp']

phy_sumo_env.Append (CPPPATH = ['.',
                                '../common',
                                'Fuzzics/include',
                                '#/intern/moto/include'
                               ])

phy_sumo_env.Append (CPPPATH = user_options_dict['SOLID_INCLUDE'])

if sys.platform=='win32':
    phy_sumo_env.Append (CXXFLAGS = ['/GR'])

phy_sumo_env.Library (target='#'+user_options_dict['BUILD_DIR']+'/lib/PHY_Sumo', source=source_files)
