#!/usr/bin/python
Import ('env')

# TODO: src_env.Append (CCFLAGS = user_options_dict['SDL_CFLAGS'])

sources = env.Glob('*.c')

incs = ' #/intern/guardedalloc ../blenlib ../makesdna ../blenkernel'
incs += ' ../include #/intern/bmfont ../imbuf ../render/extern/include'
incs += ' #/intern/bsp/extern ../radiosity/extern/include'
incs += ' #/intern/decimation/extern ../blenloader ../python'
incs += ' ../../kernel/gen_system #/intern/SoundSystem ../readstreamglue'
incs += ' ../img ../quicktime #/intern/elbeem/extern'
incs += ' #/intern/ghost #/intern/opennl/extern'

incs += ' ' + env['BF_PYTHON_INC']
incs += ' ' + env['BF_SDL_INC']
incs += ' ' + env['BF_OPENGL_INC']

defs = []

if env['WITH_BF_FREETYPE'] == 1:
    incs += ' ../ftfont'
    defs.append('INTERNATIONAL')
    defs.append('FTGL_STATIC_LIBRARY')

if env['WITH_BF_OPENEXR'] == 1:
    defs.append('WITH_OPENEXR')

if env['WITH_BF_QUICKTIME']==1:
    incs += ' ' + env['BF_QUICKTIME_INC']
    defs.append('WITH_QUICKTIME')

# TODO buildinfo
if env['BF_BUILDINFO'] == 1:
    defs.append('NAN_BUILDINFO')

env.BlenderLib ( libname = 'src', sources = sources, includes = Split(incs), defines = defs, libtype=['core', 'intern'], priority = [5, 25] )
