#!/usr/bin/python
Import ('env')

SConscript(['audaspace/SConscript',
            'string/SConscript',
            'ghost/SConscript',
            'guardedalloc/SConscript',
            'moto/SConscript',
            'memutil/SConscript/',
            'iksolver/SConscript',
            'itasc/SConscript',
            'opencolorio/SConscript',
            'opennl/SConscript',
            'mikktspace/SConscript',
            'smoke/SConscript',
            'raskter/SConscript'])

# currently only contains headers
# SConscript('container/SConscript')

if env ['WITH_BF_REMESH']:
    SConscript(['dualcon/SConscript'])

if env['WITH_BF_FLUID']:
    SConscript(['elbeem/SConscript'])

if env['WITH_BF_CYCLES']:
    SConscript(['cycles/SConscript'])

if env['WITH_BF_BOOLEAN']:
    SConscript(['bsp/SConscript'])

if env['WITH_BF_INTERNATIONAL']:
    SConscript(['locale/SConscript'])

if env['OURPLATFORM'] in ('win32-vc', 'win32-mingw', 'win64-mingw', 'linuxcross', 'win64-vc'):
    SConscript(['utfconv/SConscript'])

