#!/usr/bin/python
Import ('env')

SConscript(['audaspace/SConscript',
            'string/SConscript',
            'ghost/SConscript',
            'guardedalloc/SConscript',
            'moto/SConscript',
            'container/SConscript',
            'memutil/SConscript/',
            'decimation/SConscript',
            'iksolver/SConscript',
            'itasc/SConscript',
            'boolop/SConscript',
            'opennl/SConscript',
            'mikktspace/SConscript',
            'smoke/SConscript',
            'raskter/SConscript'])

if env ['WITH_BF_REMESH']:
    SConscript(['dualcon/SConscript'])

if env['WITH_BF_FLUID']:
    SConscript(['elbeem/SConscript'])

if env['WITH_BF_CYCLES']:
    SConscript(['cycles/SConscript'])

SConscript(['bsp/SConscript'])

if env['OURPLATFORM'] in ('win32-vc', 'win32-mingw', 'win64-mingw', 'linuxcross', 'win64-vc'):
    SConscript(['utfconv/SConscript'])
