# SPDX-FileCopyrightText: 2026 Blender Authors
#
# SPDX-License-Identifier: GPL-2.0-or-later
#
# Generated by datamodel-codegen:
#   source filename:  blender_asset_library_openapi.yaml

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Optional, Union


@dataclass
class Contact:
    name: str
    url: Optional[str] = None
    email: Optional[str] = None


@dataclass
class URLWithHash:
    url: str
    hash: str


class AssetIDTypeV1(Enum):
    action = "action"
    brush = "brush"
    cachefile = "cachefile"
    collection = "collection"
    curves = "curves"
    font = "font"
    freestylelinestyle = "freestylelinestyle"
    greasepencil = "greasepencil"
    image = "image"
    mask = "mask"
    material = "material"
    movieclip = "movieclip"
    nodetree = "nodetree"
    object = "object"
    paintcurve = "paintcurve"
    palette = "palette"
    particlesettings = "particlesettings"
    pointcloud = "pointcloud"
    scene = "scene"
    sound = "sound"
    texture = "texture"
    volume = "volume"
    workspace = "workspace"
    world = "world"


class CustomPropertyTypeV1(Enum):
    STRING = "STRING"
    INT = "INT"
    FLOAT = "FLOAT"
    ARRAY = "ARRAY"
    GROUP = "GROUP"
    DOUBLE = "DOUBLE"
    BOOLEAN = "BOOLEAN"


@dataclass
class CatalogV1:
    path: str
    uuids: list[str]
    simple_name: Optional[str] = None


@dataclass
class FileV1:
    path: str
    size_in_bytes: int
    hash: str
    blender_version: str
    url: Optional[str] = None


@dataclass
class AssetLibraryMeta:
    api_versions: dict[str, URLWithHash]
    name: str
    contact: Contact


@dataclass
class AssetLibraryIndexV1:
    schema_version: str
    asset_size_bytes: int
    asset_count: int
    file_count: int
    pages: list[URLWithHash]
    catalogs: Optional[list[CatalogV1]] = None


@dataclass
class AssetLibraryIndexPageV1:
    asset_count: int
    file_count: int
    assets: list[AssetV1]
    files: list[FileV1]


@dataclass
class AssetV1:
    name: str
    id_type: AssetIDTypeV1
    file: str
    thumbnail: Optional[URLWithHash] = None
    meta: Optional[AssetMetadataV1] = None


@dataclass
class AssetMetadataV1:
    catalog_id: Optional[str] = None
    tags: Optional[list[str]] = None
    author: Optional[str] = None
    description: Optional[str] = None
    license: Optional[str] = None
    copyright: Optional[str] = None
    custom: Optional[CustomPropertiesV1] = None


CustomPropertiesV1 = Optional[dict[str, 'CustomPropertyV1']]


@dataclass
class CustomPropertyV1:
    type: CustomPropertyTypeV1
    value: Union[CustomPropertiesV1, list, float, int, str, bool]
    itemtype: Optional[CustomPropertyTypeV1] = None
