Import ('extra_includes')
Import ('user_options_dict')
Import ('library_env')

wrblenfile_env = library_env.Copy ()

source_files = ['intern/BLO_writeblenfile.c']

wrblenfile_env.Append (CPPPATH = ['.',
                                  '../../kernel/gen_messaging',
                                  '../blenloader',
                                  '../writestreamglue',
                                  '../readstreamglue',
                                  '../readblenfile'])

wrblenfile_env.Append (CPPPATH = user_options_dict['Z_INCLUDE'])
wrblenfile_env.Append (CPPPATH = extra_includes)
wrblenfile_env.Library (target='#'+user_options_dict['BUILD_DIR']+'/lib/blender_writeblenfile', source=source_files)
