#!/usr/bin/python
Import ('env')
import btools

env['RCFLAGS'].append("-DWINDRES")
env['RCFLAGS'].append("-DBLEN_VER_RC_STR_M=" + btools.VERSION)
env['RCFLAGS'].append("-DBLEN_VER_RC_1=" + btools.VERSION[0])
env['RCFLAGS'].append("-DBLEN_VER_RC_2=" + btools.VERSION[2])
env['RCFLAGS'].append("-DBLEN_VER_RC_3=" + btools.VERSION[3])
env['RCFLAGS'].append("-DBLEN_VER_RC_4=0")

env.BlenderRes('winresource', 'winblender.rc', ['core'], priority=[95])
