#!/usr/bin/python
Import ('env')

if env['OURPLATFORM'] == 'linuxcross':
	source = 'linuxcrossblender.rcscons'
else:
	source = 'winblender.rcscons'

env.BlenderRes('winresource', source, ['core'], priority=[95])
