#!/usr/bin/python
Import ('env')

sources = env.Glob('*.c')

incs = '.'
defs = ''



if env['OURPLATFORM'] in ('win32-vc', 'win32-mingw', 'linuxcross', 'win64-vc'):
    env.BlenderLib ('bf_utfconv', sources, Split(incs), Split(defs), libtype=['intern','player'], priority=[0,0] )
