#!/usr/bin/env python
#
# ***** BEGIN GPL LICENSE BLOCK *****
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
#
# The Original Code is Copyright (C) 2006, Blender Foundation
# All rights reserved.
#
# The Original Code is: all of this file.
#
# Contributor(s): Nathan Letwory.
#
# ***** END GPL LICENSE BLOCK *****

Import ('env')

cflags=''

sources = env.Glob('intern/*.c')
sources += env.Glob('operators/*.c')
sources += env.Glob('tools/*.c')

incs = [
    './',
    '../blenfont',
    '../blenlib',
    '../makesdna',
    '../blenkernel',
    '#/intern/guardedalloc',
    '#/extern/bullet2/src',
    '#/extern/rangetree',
    '#/intern/opennl/extern'
    ]

defs = []

if env['WITH_BF_BULLET']:
    defs.append('WITH_BULLET')

if env['WITH_BF_INTERNATIONAL']:
    defs.append('WITH_INTERNATIONAL')

if env['WITH_BF_FREESTYLE']:
    defs.append('WITH_FREESTYLE')

env.BlenderLib ( libname = 'bf_bmesh', sources = sources, includes = Split(incs), libtype = ['core','player'], defines=defs, priority=[100, 100], compileflags=cflags )
