/* SPDX-FileCopyrightText: 2026 Blender Authors
 *
 * SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#include "types.hh"

namespace lexit {

/* Associates a token type to each ASCII character. */
const CharClass char_class_table[128] = {
    /* 0x00, '\0' */ CharClass::None,
    /* 0x01, SOH  */ CharClass::None,
    /* 0x02, STX  */ CharClass::None,
    /* 0x03, ETX  */ CharClass::None,
    /* 0x04, EOT  */ CharClass::None,
    /* 0x05, ENQ  */ CharClass::None,
    /* 0x06, ACK  */ CharClass::None,
    /* 0x07, '\a' */ CharClass::None,
    /* 0x08, '\b' */ CharClass::None,
    /* 0x09, '\t' */ CharClass::WhiteSpace,
    /* 0x0A, '\n' */ CharClass::Separator,
    /* 0x0B, '\v' */ CharClass::None,
    /* 0x0C, '\f' */ CharClass::None,
    /* 0x0D, '\r' */ CharClass::Separator,
    /* 0x0E, SO   */ CharClass::None,
    /* 0x0F, SI   */ CharClass::None,
    /* 0x10, DLE  */ CharClass::None,
    /* 0x11, DC1  */ CharClass::None,
    /* 0x12, DC2  */ CharClass::None,
    /* 0x13, DC3  */ CharClass::None,
    /* 0x14, DC4  */ CharClass::None,
    /* 0x15, NAK  */ CharClass::None,
    /* 0x16, SYN  */ CharClass::None,
    /* 0x17, ETB  */ CharClass::None,
    /* 0x18, CAN  */ CharClass::None,
    /* 0x19, EM   */ CharClass::None,
    /* 0x1A, SUB  */ CharClass::None,
    /* 0x1B, ESC  */ CharClass::None,
    /* 0x1C, FS   */ CharClass::None,
    /* 0x1D, GS   */ CharClass::None,
    /* 0x1E, RS   */ CharClass::None,
    /* 0x1F, US   */ CharClass::None,

    /* 0x20, ' '  */ CharClass::WhiteSpace,
    /* 0x21, '!'  */ CharClass::MultiTok,
    /* 0x22, '"'  */ CharClass::Separator,
    /* 0x23, '#'  */ CharClass::Separator,
    /* 0x24, '$'  */ CharClass::Separator,
    /* 0x25, '%'  */ CharClass::MultiTok,
    /* 0x26, '&'  */ CharClass::MultiTok,
    /* 0x27, '\'' */ CharClass::Separator,
    /* 0x28, '('  */ CharClass::Separator,
    /* 0x29, ')'  */ CharClass::Separator,
    /* 0x2A, '*'  */ CharClass::MultiTok,
    /* 0x2B, '+'  */ CharClass::MultiTok,
    /* 0x2C, ','  */ CharClass::Separator,
    /* 0x2D, '-'  */ CharClass::MultiTok,
    /* 0x2E, '.'  */ CharClass::MultiTok,
    /* 0x2F, '/'  */ CharClass::MultiTok,
    /* 0x30, '0'  */ CharClass::Numeric,
    /* 0x31, '1'  */ CharClass::Numeric,
    /* 0x32, '2'  */ CharClass::Numeric,
    /* 0x33, '3'  */ CharClass::Numeric,
    /* 0x34, '4'  */ CharClass::Numeric,
    /* 0x35, '5'  */ CharClass::Numeric,
    /* 0x36, '6'  */ CharClass::Numeric,
    /* 0x37, '7'  */ CharClass::Numeric,
    /* 0x38, '8'  */ CharClass::Numeric,
    /* 0x39, '9'  */ CharClass::Numeric,
    /* 0x3A, ':'  */ CharClass::Separator,
    /* 0x3B, ';'  */ CharClass::Separator,
    /* 0x3C, '<'  */ CharClass::MultiTok,
    /* 0x3D, '='  */ CharClass::MultiTok,
    /* 0x3E, '>'  */ CharClass::MultiTok,
    /* 0x3F, '?'  */ CharClass::Separator,

    /* 0x40, '@'  */ CharClass::Separator,
    /* 0x41, 'A'  */ CharClass::Alpha,
    /* 0x42, 'B'  */ CharClass::Alpha,
    /* 0x43, 'C'  */ CharClass::Alpha,
    /* 0x44, 'D'  */ CharClass::Alpha,
    /* 0x45, 'E'  */ CharClass::Alpha,
    /* 0x46, 'F'  */ CharClass::Alpha,
    /* 0x47, 'G'  */ CharClass::Alpha,
    /* 0x48, 'H'  */ CharClass::Alpha,
    /* 0x49, 'I'  */ CharClass::Alpha,
    /* 0x4A, 'J'  */ CharClass::Alpha,
    /* 0x4B, 'K'  */ CharClass::Alpha,
    /* 0x4C, 'L'  */ CharClass::Alpha,
    /* 0x4D, 'M'  */ CharClass::Alpha,
    /* 0x4E, 'N'  */ CharClass::Alpha,
    /* 0x4F, 'O'  */ CharClass::Alpha,
    /* 0x50, 'P'  */ CharClass::Alpha,
    /* 0x51, 'Q'  */ CharClass::Alpha,
    /* 0x52, 'R'  */ CharClass::Alpha,
    /* 0x53, 'S'  */ CharClass::Alpha,
    /* 0x54, 'T'  */ CharClass::Alpha,
    /* 0x55, 'U'  */ CharClass::Alpha,
    /* 0x56, 'V'  */ CharClass::Alpha,
    /* 0x57, 'W'  */ CharClass::Alpha,
    /* 0x58, 'X'  */ CharClass::Alpha,
    /* 0x59, 'Y'  */ CharClass::Alpha,
    /* 0x5A, 'Z'  */ CharClass::Alpha,
    /* 0x5B, '['  */ CharClass::Separator,
    /* 0x5C, '\\' */ CharClass::Separator,
    /* 0x5D, ']'  */ CharClass::Separator,
    /* 0x5E, '^'  */ CharClass::MultiTok,
    /* 0x5F, '_'  */ CharClass::Alpha, /* Can also start identifiers. */

    /* 0x60, '`'  */ CharClass::Separator,
    /* 0x61, 'a'  */ CharClass::Alpha,
    /* 0x62, 'b'  */ CharClass::Alpha,
    /* 0x63, 'c'  */ CharClass::Alpha,
    /* 0x64, 'd'  */ CharClass::Alpha,
    /* 0x65, 'e'  */ CharClass::Alpha,
    /* 0x66, 'f'  */ CharClass::Alpha,
    /* 0x67, 'g'  */ CharClass::Alpha,
    /* 0x68, 'h'  */ CharClass::Alpha,
    /* 0x69, 'i'  */ CharClass::Alpha,
    /* 0x6A, 'j'  */ CharClass::Alpha,
    /* 0x6B, 'k'  */ CharClass::Alpha,
    /* 0x6C, 'l'  */ CharClass::Alpha,
    /* 0x6D, 'm'  */ CharClass::Alpha,
    /* 0x6E, 'n'  */ CharClass::Alpha,
    /* 0x6F, 'o'  */ CharClass::Alpha,
    /* 0x70, 'p'  */ CharClass::Alpha,
    /* 0x71, 'q'  */ CharClass::Alpha,
    /* 0x72, 'r'  */ CharClass::Alpha,
    /* 0x73, 's'  */ CharClass::Alpha,
    /* 0x74, 't'  */ CharClass::Alpha,
    /* 0x75, 'u'  */ CharClass::Alpha,
    /* 0x76, 'v'  */ CharClass::Alpha,
    /* 0x77, 'w'  */ CharClass::Alpha,
    /* 0x78, 'x'  */ CharClass::Alpha,
    /* 0x79, 'y'  */ CharClass::Alpha,
    /* 0x7A, 'z'  */ CharClass::Alpha,
    /* 0x7B, '{'  */ CharClass::Separator,
    /* 0x7C, '|'  */ CharClass::MultiTok,
    /* 0x7D, '}'  */ CharClass::Separator,
    /* 0x7E, '~'  */ CharClass::Separator,
    /* 0x7F, Del  */ CharClass::None,
};

}  // namespace lexit
