#!/usr/bin/python
Import ('env')

sources = env.Glob('*.c')

incs = '../include ../../blenlib ../../blenkernel ../../makesdna ../../imbuf'
incs += ' ../../windowmanager #/intern/guardedalloc'
incs += ' ../../makesrna'
incs += ' #/intern/audaspace/intern'
if env['WITH_BF_PYTHON']:
    incs += ' ' + env['BF_PYTHON_INC']

defs = []

env.BlenderLib ( 'bf_editors_sound', sources, Split(incs), defs, libtype=['core'], priority=[35] )
