#!/usr/bin/python
Import ('env')

sources = env.Glob('*.cpp') #'NG_NetworkMessage.cpp NG_NetworkObject.cpp NG_NetworkScene.cpp'

incs = '. #source/kernel/gen_system #intern/string #intern/moto/include'

env.BlenderLib ( 'bf_ngnetwork', sources, Split(incs), [], libtype=['core','player'], priority=[400,130] )
