#!/usr/bin/python
Import ('env')

sources = env.Glob('*.c') + env.Glob('*.cpp')

incs = '../include ../../blenlib ../../blenkernel ../../makesdna ../../imbuf'
incs += ' ../../windowmanager #/intern/guardedalloc #/extern/glew/include'
incs += ' ../../makesrna'
incs += ' #extern/recastnavigation/Recast/Include'
incs += ' ../../blenloader'

if not env['WITH_BF_GAMEENGINE']:
    sources.remove('navmesh_conversion.cpp')

env.BlenderLib ( 'bf_editors_util', sources, Split(incs), [], libtype=['core','player'], priority=[130,210] )
