#!/usr/bin/python
import sys

Import ('env')

sources = env.Glob('*.cpp')
defs = [ 'GLEW_STATIC' ]

incs = '. #source/blender/python/generic' # Only for Mathutils! and bpy_internal_import.h, be very careful

incs += ' #source/kernel/gen_system #intern/string #intern/guardedalloc'
incs += ' #source/gameengine/Rasterizer/RAS_OpenGLRasterizer'
incs += ' #intern/audaspace/intern #source/gameengine/Converter'
incs += ' #source/gameengine/BlenderRoutines #source/blender/imbuf #intern/moto/include'
incs += ' #source/gameengine/Ketsji #source/gameengine/Ketsji/KXNetwork #source/blender/blenlib'
incs += ' #source/blender/blenkernel #source/blender #source/blender/editors/include'
incs += ' #source/blender/makesdna #source/blender/python #source/gameengine/Rasterizer'
incs += ' #source/gameengine/GameLogic #source/gameengine/Expressions #source/gameengine/Network'
incs += ' #source/gameengine/SceneGraph #source/gameengine/Physics/common #source/gameengine/Physics/Bullet'
incs += ' #source/gameengine/Physics/Dummy'
incs += ' #source/blender/misc #source/blender/blenloader #extern/glew/include #source/blender/gpu'

incs += ' ' + env['BF_BULLET_INC']
incs += ' ' + env['BF_OPENGL_INC']

if  env['WITH_BF_SDL']:
    incs += ' ' + env['BF_SDL_INC']
else:
	defs.append('DISABLE_SDL')

if env['WITH_BF_PYTHON']:
	incs += ' ' + env['BF_PYTHON_INC']
else:
	defs.append('DISABLE_PYTHON')

if env['WITH_FFMPEG']:
	defs.append('DWITH_FFMPEG')
	
if env['OURPLATFORM'] in ('win32-vc', 'win64-vc', 'win32-mingw'):
	if env['BF_DEBUG']:
		defs.append('_DEBUG') # for Python

env.BlenderLib ( 'bf_ketsji', sources, Split(incs), defs, libtype=['core','player'], priority=[320,45], cxx_compileflags=env['BGE_CXXFLAGS'])
