#!/usr/bin/python
Import ('user_options_dict')
Import ('library_env')

renderconv_env = library_env.Copy ()

source_files = ['intern/convertBlenderScene.c']

renderconv_env.Append (CPPPATH = ['.',
                                  '../blenlib',
                                  '#/intern/guardedalloc',
                                  '../makesdna',
                                  '../blenkernel',
                                  '../include',
                                  '../render/extern/include',
                                  '../python'])

renderconv_env.Library (target='#'+user_options_dict['BUILD_DIR']+'/lib/blender_renderconverter', source=source_files)
