#!/usr/bin/env python
#
# ***** BEGIN GPL LICENSE BLOCK *****
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
#
# The Original Code is Copyright (C) 2006, Blender Foundation
# All rights reserved.
#
# The Original Code is: all of this file.
#
# Contributor(s): Nathan Letwory.
#
# ***** END GPL LICENSE BLOCK *****

Import ('env')

# all source generated now
# sources = env.Glob('*.c')
sources = []
incs = []
defs = []

# generated data files
import os
sources.extend((
    os.path.join(env['DATA_SOURCES'], "bfont.pfb.c"),
    os.path.join(env['DATA_SOURCES'], "bfont.ttf.c"),
    os.path.join(env['DATA_SOURCES'], "bmonofont.ttf.c"),

    os.path.join(env['DATA_SOURCES'], "splash.png.c"),
    os.path.join(env['DATA_SOURCES'], "splash_2x.png.c"),
    os.path.join(env['DATA_SOURCES'], "blender_icons16.png.c"),
    os.path.join(env['DATA_SOURCES'], "blender_icons32.png.c"),
    os.path.join(env['DATA_SOURCES'], "prvicons.png.c"),

    os.path.join(env['DATA_SOURCES'], "startup.blend.c"),
    os.path.join(env['DATA_SOURCES'], "preview.blend.c"),
    os.path.join(env['DATA_SOURCES'], "preview_cycles.blend.c"),

    os.path.join(env['DATA_SOURCES'], "add.png.c"),
    os.path.join(env['DATA_SOURCES'], "blob.png.c"),
    os.path.join(env['DATA_SOURCES'], "blur.png.c"),
    os.path.join(env['DATA_SOURCES'], "clay.png.c"),
    os.path.join(env['DATA_SOURCES'], "claystrips.png.c"),
    os.path.join(env['DATA_SOURCES'], "clone.png.c"),
    os.path.join(env['DATA_SOURCES'], "crease.png.c"),
    os.path.join(env['DATA_SOURCES'], "darken.png.c"),
    os.path.join(env['DATA_SOURCES'], "draw.png.c"),
    os.path.join(env['DATA_SOURCES'], "fill.png.c"),
    os.path.join(env['DATA_SOURCES'], "flatten.png.c"),
    os.path.join(env['DATA_SOURCES'], "grab.png.c"),
    os.path.join(env['DATA_SOURCES'], "inflate.png.c"),
    os.path.join(env['DATA_SOURCES'], "layer.png.c"),
    os.path.join(env['DATA_SOURCES'], "lighten.png.c"),
    os.path.join(env['DATA_SOURCES'], "mask.png.c"),
    os.path.join(env['DATA_SOURCES'], "mix.png.c"),
    os.path.join(env['DATA_SOURCES'], "multiply.png.c"),
    os.path.join(env['DATA_SOURCES'], "nudge.png.c"),
    os.path.join(env['DATA_SOURCES'], "pinch.png.c"),
    os.path.join(env['DATA_SOURCES'], "scrape.png.c"),
    os.path.join(env['DATA_SOURCES'], "smear.png.c"),
    os.path.join(env['DATA_SOURCES'], "smooth.png.c"),
    os.path.join(env['DATA_SOURCES'], "snake_hook.png.c"),
    os.path.join(env['DATA_SOURCES'], "soften.png.c"),
    os.path.join(env['DATA_SOURCES'], "subtract.png.c"),
    os.path.join(env['DATA_SOURCES'], "texdraw.png.c"),
    os.path.join(env['DATA_SOURCES'], "thumb.png.c"),
    os.path.join(env['DATA_SOURCES'], "twist.png.c"),
    os.path.join(env['DATA_SOURCES'], "vertexdraw.png.c"),

    os.path.join(env['DATA_SOURCES'], "mc01.jpg.c"),
    os.path.join(env['DATA_SOURCES'], "mc02.jpg.c"),
    os.path.join(env['DATA_SOURCES'], "mc03.jpg.c"),
    os.path.join(env['DATA_SOURCES'], "mc04.jpg.c"),
    os.path.join(env['DATA_SOURCES'], "mc05.jpg.c"),
    os.path.join(env['DATA_SOURCES'], "mc06.jpg.c"),
    os.path.join(env['DATA_SOURCES'], "mc07.jpg.c"),
    os.path.join(env['DATA_SOURCES'], "mc08.jpg.c"),
    os.path.join(env['DATA_SOURCES'], "mc09.jpg.c"),
    os.path.join(env['DATA_SOURCES'], "mc10.jpg.c"),
    os.path.join(env['DATA_SOURCES'], "mc11.jpg.c"),
    os.path.join(env['DATA_SOURCES'], "mc12.jpg.c"),
    os.path.join(env['DATA_SOURCES'], "mc13.jpg.c"),
    os.path.join(env['DATA_SOURCES'], "mc14.jpg.c"),
    os.path.join(env['DATA_SOURCES'], "mc15.jpg.c"),
    os.path.join(env['DATA_SOURCES'], "mc16.jpg.c"),
    os.path.join(env['DATA_SOURCES'], "mc17.jpg.c"),
    os.path.join(env['DATA_SOURCES'], "mc18.jpg.c"),
    os.path.join(env['DATA_SOURCES'], "mc19.jpg.c"),
    os.path.join(env['DATA_SOURCES'], "mc20.jpg.c"),
    os.path.join(env['DATA_SOURCES'], "mc21.jpg.c"),
    os.path.join(env['DATA_SOURCES'], "mc22.jpg.c"),
    os.path.join(env['DATA_SOURCES'], "mc23.jpg.c"),
    os.path.join(env['DATA_SOURCES'], "mc24.jpg.c"),

    ))

env.BlenderLib ( 'bf_editor_datafiles', sources, incs, defs, libtype=['core', 'player'], priority=[235, 30] )
