#!/usr/bin/python
Import ('env')

sources = env.Glob('*.c')

incs = '../include ../../blenfont ../../blenlib ../../blenkernel ../../makesdna ../../makesrna ../../imbuf'
incs += ' ../../windowmanager #/intern/guardedalloc #/extern/glew/include ../../blenloader'

defs = []

if env['WITH_BF_INTERNATIONAL']:
    defs.append('WITH_INTERNATIONAL')

env.BlenderLib ( 'bf_editors_space_nla', sources, Split(incs), defs, libtype=['core'], priority=[85] )
