#!/usr/bin/python
Import ('env')

sources = env.Glob('intern/*.c')

#incs = '#/intern/guardedalloc ../blenlib ../makesdna ../blenkernel'
#incs += ' ../imbuf ../editors/include ../render/extern/include ../render/intern/include'

incs = '. ../editors/include ../python ../makesdna ../blenlib ../blenkernel'
incs += ' ../nodes ../imbuf ../blenloader ../render/extern/include'
incs += ' ../ftfont ../radiosity/extern/include ../../kernel/gen_system'

incs += ' #/intern/guardedalloc #/intern/memutil #/intern/ghost #/intern/bmfont'
incs += ' #/intern/elbeem #/extern/glew/include'
env.BlenderLib ( 'bf_windowmanager', sources, Split(incs), [], libtype=['core','intern'], priority=[45, 45] )
