#!/usr/bin/python
import sys
Import ('env')

source_files = ['GPG_Application.cpp',
                'GPG_Canvas.cpp',
                'GPG_ghost.cpp',
                'GPG_KeyboardDevice.cpp',
                'GPG_System.cpp']

incs = ['.',
        '#intern/string',
        '#intern/ghost',
        '#intern/guardedalloc',
        '#intern/moto/include',
        '#source/gameengine/Rasterizer/RAS_OpenGLRasterizer',
        '#source/kernel/gen_system',
        '#source/kernel/gen_messaging',
        '#source/gameengine/Converter',
        '#source/blender/imbuf',
        '#source/gameengine/Ketsji',
        '#source/blender/blenlib',
        '#source/blender/blenkernel',
        '#source/blender/readblenfile',
        '#source/blender',
        '#source/blender/include',
        '#source/blender/makesdna',
        '#source/blender/makesrna',
        '#source/gameengine/BlenderRoutines',
        '#source/gameengine/Rasterizer',
        '#source/gameengine/GameLogic',
        '#source/gameengine/Expressions',
        '#source/gameengine/Network',
        '#source/gameengine/SceneGraph',
        '#source/gameengine/Physics/common',
        '#source/gameengine/Network/LoopBackNetwork',
        '#source/gameengine/GamePlayer/common',
        '#source/blender/misc',
        '#source/blender/blenloader',
        '#source/blender/gpu',
        '#extern/glew/include']

incs += Split(env['BF_PYTHON_INC'])

cxxflags = []
if env['OURPLATFORM'] in ('win32-vc', 'win64-vc'):
	cxxflags.append ('/GR')
	cxxflags.append ('/O2')
	cxxflags.append ('/EHsc')

defs = ''
if env['WITH_BF_FFMPEG']:
    defs += ' WITH_FFMPEG'

env.BlenderLib (libname='gp_ghost', sources=source_files, includes = incs, defines = Split(defs), libtype='player',priority=5, cxx_compileflags=cxxflags)
