import sys
Import ('user_options_dict')
Import ('library_env')

ras_rasterizer_env = library_env.Copy ()

source_files = ['RAS_BucketManager.cpp',
                'RAS_FramingManager.cpp',
                'RAS_IPolygonMaterial.cpp',
                'RAS_IRenderTools.cpp',
                'RAS_MaterialBucket.cpp',
                'RAS_MeshObject.cpp',
                'RAS_Polygon.cpp',
                'RAS_TexVert.cpp',
                'RAS_texmatrix.cpp']

ras_rasterizer_env.Append (CPPPATH=['.',
                                    '#source/kernel/gen_system',
                                    '#intern/string',
                                    '#intern/moto/include'
                                   ])

if sys.platform=='win32':
	ras_rasterizer_env.Append ( CCFLAGS =['/Ox'])

ras_rasterizer_env.Library (target='#'+user_options_dict['BUILD_DIR']+'/lib/RAS_rasterizer', source=source_files)
