#!/usr/bin/python
Import ('env')

sources = env.Glob('*.cpp')


incs = '. #intern/guardedalloc #source/kernel/gen_system #intern/string #intern/moto/include #source/gameengine/BlenderRoutines #extern/glew/include #source/gameengine/Expressions #source/gameengine/SceneGraph #source/blender/blenkernel #source/blender/makesdna'

defs = [ 'GLEW_STATIC' ]

if env['WITH_BF_PYTHON']:
	incs += ' ' + env['BF_PYTHON_INC']
else:
	defs.append('DISABLE_PYTHON')

env.BlenderLib ( 'bf_rasterizer', sources, Split(incs), defs, libtype=['core','player'], priority=[350,70], cxx_compileflags=env['BGE_CXXFLAGS'])
