#!/usr/bin/python
Import ('env')

source_files = ['apple/quicktime_import.c',
                'apple/quicktime_export.c']

incs  = ['.',
		 '../quicktime',
		 '../makesdna',
		 '#/intern/guardedalloc',
		 '../blenlib',
		 '../blenkernel',
		 '../avi',
		 '../imbuf',
		 '../imbuf/intern',
		 '../blenloader',
		 '../render/extern/include',
		 '../editors/include']

incs.append(env['BF_QUICKTIME_INC'])

types = ['core','player']
priorities = [200,235]

env.BlenderLib ('bf_quicktime', sources=source_files, includes=incs, defines=['WITH_QUICKTIME'], libtype=types, priority=priorities)
