Import ('extra_includes')
Import ('user_options_dict')
Import ('library_env')

quicktime_env = library_env.Copy ()

quicktime_env.Append (CPPPATH = extra_includes)

source_files = ['apple/quicktime_import.c',
                'apple/quicktime_export.c']

quicktime_env.Append (CPPPATH = ['.',
                                 '../makesdna',
                                 '#/intern/guardedalloc',
                                 '../blenlib',
                                 '../blenkernel',
                                 '../avi',
                                 '../imbuf',
                                 '../imbuf/intern',
                                 '../blenloader',
                                 '../render/extern/include'])

quicktime_env.Library (target='#'+user_options_dict['BUILD_DIR']+'/lib/blender_quicktime', source=source_files)
