Import ('extra_includes')
Import ('user_options_dict')
Import ('library_env')

ftf_env = library_env.Copy ()

source_files = ['intern/FTF_Api.cpp',
                'intern/FTF_TTFont.cpp']

include_paths = ['.',
		'intern',
		'../blenkernel',
		'../blenlib',
		'../makesdna']
                 
ftf_env.Append(CPPPATH = extra_includes)
ftf_env.Append(CPPPATH = include_paths)
ftf_env.Prepend (CPPPATH = user_options_dict['FTGL_INCLUDE'])
ftf_env.Prepend (CPPPATH = user_options_dict['FREETYPE_INCLUDE'])
ftf_env.Prepend (CPPPATH = user_options_dict['GETTEXT_INCLUDE'])
ftf_env.Append(CPPDEFINES = 'FTGL_STATIC_LIBRARY')
ftf_env.Library (target='#'+user_options_dict['BUILD_DIR']+'/lib/blender_FTF', source=source_files)
