#!/usr/bin/python
import sys
Import ('env')

sources = env.Glob('intern/*.cpp')

incs = '. intern ../blenkernel ../blenlib ../makesdna'
incs += ' ' + env['BF_FTGL_INC']
incs += ' ' + env['BF_FREETYPE_INC']
incs += ' ' + env['BF_GETTEXT_INC']
                 
defs = 'FTGL_STATIC_LIBRARY'
if sys.platform == 'win32':
	defs += ' _WIN32 USE_GETTEXT_DLL'
env.BlenderLib ( 'blender_FTF', sources, Split(incs), Split(defs), libtype='international', priority=0 )
