#!/usr/bin/python
Import ('user_options_dict')
Import ('library_env')

ng_loopbacknetwork_env = library_env.Copy ()

source_files = ['NG_LoopBackNetworkDeviceInterface.cpp']

ng_loopbacknetwork_env.Append (CPPPATH=['.',
                                        '#source/kernel/gen_system',
                                        '#intern/string',
                                        '#source/gameengine/Network',
                                       ])

ng_loopbacknetwork_env.Library (target='#'+user_options_dict['BUILD_DIR']+'/lib/NG_loopbacknetwork', source=source_files)
