#!/usr/bin/python
Import ('env')

sources = 'NG_LoopBackNetworkDeviceInterface.cpp'

incs = '. #source/kernel/gen_system #intern/string #source/gameengine/Network'

env.BlenderLib ( 'bf_loopbacknetwork', Split(sources), Split(incs), defines=[],libtype=['core','player'], priority=[400,135] )
