#!/usr/bin/python
Import ('env')

sources = env.Glob('intern/*.cpp')

incs = '. intern extern ../moto/include ../container ../memutil'

env.BlenderLib ('blender_bop', sources, Split(incs) , [], libtype='common', priority = 5 )
