#!/usr/bin/python
Import ('env')

sources = env.Glob('intern/*.cpp')

incs = '. intern extern ../moto/include ../container ../memutil'
incs += ' ../../source/blender/makesdna ../../intern/guardedalloc'
incs += ' ../../source/blender/blenlib'

if (env['OURPLATFORM'] == 'win32-mingw'):
    env.BlenderLib ('blender_bop', sources, Split(incs) , [], libtype=['common','intern'], priority = [30,85] )
else:
    env.BlenderLib ('blender_bop', sources, Split(incs) , [], libtype='common', priority = 5 )

