#!/usr/bin/python
Import ('env')

objs = []

o = SConscript('intern/SConscript')
objs.append (o)

incs = '#/intern/guardedalloc'

env.BlenderLib ( 'bf_dna', objs, Split(incs), [], libtype=['common','player'], priority = [10, 215] )
