#!/usr/bin/python
Import ('env')

sources = env.Glob('intern/*.c')

incs = '. ../makesdna #/intern/guardedalloc ../blenlib'
incs += ' ../avi ../quicktime ../blenkernel'

incs += ' ' + env['BF_JPEG_INC']
incs += ' ' + env['BF_PNG_INC']
incs += ' ' + env['BF_TIFF_INC']
incs += ' ' + env['BF_ZLIB_INC']

defs = []

if env['WITH_BF_OPENEXR'] == 1:
    defs.append('WITH_OPENEXR')

if env['WITH_BF_QUICKTIME']==1:
	incs += ' ' + env['BF_QUICKTIME_INC']
	defs.append('WITH_QUICKTIME')

env.BlenderLib ( libname = 'blender_imbuf', sources = sources, includes = Split(incs), defines = defs, libtype='core', priority = 80 )
