#
# $Id$
# Copyright (C) 2001 NaN Technologies B.V.

LIBNAME = fuzzics
DIR     = $(OCGDIR)/gameengine/blphys/$(LIBNAME)

include nan_compile.mk

CCFLAGS += $(LEVEL_1_CPP_WARNINGS)

CPPFLAGS += -I../include -I$(NAN_MOTO)/include -I../../include
CPPFLAGS += -I$(NAN_SOLID)/include

