#!/usr/bin/python
Import ('env')

sources = env.Glob('intern/*.cpp')

incs = '#/intern/guardedalloc ../blenlib ../makesdna ../blenkernel'
incs += ' ../imbuf ../include ../render/extern/include ../render/intern/include'

env.BlenderLib ( 'blender_yafray', sources, Split(incs), [], libtype='blender', priority=5 )
