yafray_env = Environment()

# Import the C flags set in the SConstruct file
Import ('cflags')
Import ('cxxflags')
Import ('defines')
Import ('user_options_dict')
yafray_env.Append (CCFLAGS = cflags)
yafray_env.Append (CXXFLAGS = cxxflags)
yafray_env.Append (CPPDEFINES = defines)

source_files = ['intern/yafray_Render.cpp',
                'intern/export_File.cpp',
                'intern/api.cpp']

yafray_env.Append (CPPPATH = ['#/intern/guardedalloc',
                              '../blenlib',
                              '../makesdna',
                              '../blenkernel',
                              '../imbuf',
                              '../render/extern/include'])

yafray_env.Library (target='#'+user_options_dict['BUILD_DIR']+'/lib/blender_yafray', source=source_files)
