#!/usr/bin/python
Import ('env')

SConscript(['blender/SConscript',
			'kernel/SConscript',
			'creator/SConscript'])
if env['WITH_BF_GAMEENGINE']:
	SConscript (['gameengine/SConscript'])
	
if env['OURPLATFORM'] in ('win32-vc', 'win32-mingw'):
	SConscript (['icons/SConscript'])
