Import ('user_options_dict')
Import ('library_env')

phy_physics_env = library_env.Copy ()

source_files = ['PHY_IMotionState.cpp',
                'PHY_IPhysicsController.cpp',
                'PHY_IPhysicsEnvironment.cpp']

phy_physics_env.Append (CPPPATH = ['.',
                                   '../Dummy',
                                   '#intern/moto/include'
                                  ])

phy_physics_env.Library (target='#'+user_options_dict['BUILD_DIR']+'/lib/PHY_Physics', source=source_files)
