phy_physics_env = Environment()

# Import the C flags set in the SConstruct file
Import ('cflags')
Import ('cxxflags')
Import ('defines')
Import ('user_options_dict')
phy_physics_env.Append (CCFLAGS = cflags)
phy_physics_env.Append (CXXFLAGS = cxxflags)
phy_physics_env.Append (CPPDEFINES = defines)

source_files = ['PHY_IMotionState.cpp',
                'PHY_IPhysicsController.cpp',
                'PHY_IPhysicsEnvironment.cpp']

phy_physics_env.Append (CPPPATH = ['.',
                                   '../Dummy'
                                  ])

phy_physics_env.Library (target='#'+user_options_dict['BUILD_DIR']+'/lib/PHY_Physics', source=source_files)
