#!/usr/bin/python
Import ('env')

sources = env.Glob('*.c')

incs = '../include ../../blenlib ../../blenkernel ../../makesdna ../../imbuf'
incs += ' ../../blenloader ../../makesrna ../../blenfont'
incs += ' ../../render/extern/include'
incs += ' ../../windowmanager #/intern/guardedalloc #/extern/glew/include'

defs = []

if env['WITH_BF_OPENJPEG']:
    defs.append('WITH_OPENJPEG')

env.BlenderLib ( 'bf_editors_space_file', sources, Split(incs), defs, libtype=['core'], priority=[115] )
