#!/usr/bin/python
Import ('env')

sources = env.Glob('*.c')

incs = '../include ../../blenlib ../../blenkernel ../../makesdna ../../imbuf'
incs += ' ../../blenloader #intern/bmfont ../../makesrna'
incs += ' ../../render/extern/include '
incs += ' ../../windowmanager #/intern/guardedalloc #/extern/glew/include'

env.BlenderLib ( 'bf_editors_space_file', sources, Split(incs), [], libtype=['core'], priority=[115] )
