import bpy
material = bpy.context.object.active_material
gpcolor = material.grease_pencil

gpcolor.mode = 'LINE'
gpcolor.stroke_style = 'SOLID'
gpcolor.color = (0.0, 0.0, 0.0, 1.0)
gpcolor.stroke_image = None
gpcolor.pixel_size = 100.0
gpcolor.use_stroke_pattern = False
gpcolor.use_stroke_texture_mix = False
gpcolor.mix_stroke_factor = 0.0
gpcolor.alignment_mode = 'PATH'
gpcolor.fill_style = 'SOLID'
gpcolor.fill_color = (0.5, 0.5, 0.5, 0.0)
gpcolor.fill_image = None
gpcolor.gradient_type = 'LINEAR'
gpcolor.mix_color = (1.0, 1.0, 1.0, 0.2)
gpcolor.mix_factor = 0.0
gpcolor.flip = False
gpcolor.pattern_shift = (0.0, 0.0)
gpcolor.pattern_scale = (1.0, 1.0)
gpcolor.pattern_radius = 0.5
gpcolor.pattern_angle = 0.0
gpcolor.pattern_gridsize = 0.1
gpcolor.use_fill_pattern = False
gpcolor.texture_offset = (0.0, 0.0)
gpcolor.texture_scale = (1.0, 1.0)
gpcolor.texture_angle = 0.0
gpcolor.texture_opacity = 1.0
gpcolor.texture_clamp = False
gpcolor.use_fill_texture_mix = False
gpcolor.mix_factor = 0.0
gpcolor.show_stroke = True
gpcolor.show_fill = False
