#!/usr/bin/python
import sys

Import ('env')

sources = env.Glob('*.cpp')

incs = '. #source/gameengine/Ketsji #source/gameengine/Expressions'
incs += ' #source/gameengine/GameLogic #source/gameengine/SceneGraph #source/gameengine/Rasterizer'
incs += ' #source/gameengine/Rasterizer/RAS_OpenGLRasterizer'
incs += ' #source/gameengine/BlenderRoutines'
incs += ' #source/blender/include #source/blender/blenlib #source/blender/blenkernel'
incs += ' #source/blender/makesdna #source/blender/imbuf #source/blender/python'
incs += ' #source/blender/gpu #source/kernel/gen_system #intern/string #intern/moto/include'
incs += ' #intern/guardedalloc #intern/SoundSystem'
incs += ' #extern/glew/include'

cflags = []
defs = ''
if env['OURPLATFORM'] == 'win32-vc':
	cflags.append('/GR')
	cflags.append('/Ox')

incs += ' ' + env['BF_PYTHON_INC']
#incs += ' ' + env['BF_OPENGL_INC']

if env['WITH_BF_FFMPEG']:
    defs += ' WITH_FFMPEG'
    incs += ' ' + env['BF_FFMPEG_INC']
    defs += ' __STDC_CONSTANT_MACROS'

env.BlenderLib ( 'bf_videotex', sources, Split(incs), Split(defs), libtype=['game','player'], priority=[25, 72], compileflags = cflags )
