#!/usr/bin/python

Import('env')

sources = env.Glob('*.cpp')

incs = '.'
incs += ' ' + env['BF_OCIO_INC']

env.BlenderLib( 'bf_intern_opencolorio', sources, Split(incs), [], libtype=['extern','player'], priority=[10, 185])
