Import ('user_options_dict')
Import ('library_env')

bmfont_env = library_env.Copy ()

source_files = ['intern/BMF_Api.cpp',
                'intern/BMF_BitmapFont.cpp',
                'intern/BMF_font_helv10.cpp',
                'intern/BMF_font_helv12.cpp',
                'intern/BMF_font_helvb10.cpp',
                'intern/BMF_font_helvb12.cpp',
                'intern/BMF_font_helvb14.cpp',
                'intern/BMF_font_helvb8.cpp',
                'intern/BMF_font_scr12.cpp',
                'intern/BMF_font_scr14.cpp',
                'intern/BMF_font_scr15.cpp']

bmfont_env.Append (CPPPATH = ['.',
                              'intern'])

bmfont_env.Library (target='#'+user_options_dict['BUILD_DIR']+'/lib/blender_BMF', source=source_files)
