#!/usr/bin/python
Import ('env')

source_files = env.Glob('*.c')

incs = ['.',
    '../../../blenkernel',
    '../../../blenloader',
    '../../',
    '..',
    '../../../blenlib',
    'intern/include',
    '#/intern/guardedalloc',
    '../../../makesdna']

defs = []

if env['WITH_BF_CINEON']:
    defs.append('WITH_CINEON')

env.BlenderLib ('bf_imbuf_cineon', source_files, incs, defs, libtype=['core','player'], priority = [220,175])
