#!/usr/bin/python
Import ('env')

#source_files = ['cineon_dpx.c', 'cineonlib.c']
source_files = env.Glob('*.c')

incs = ['.',
	'../../../blenkernel',
	'../../',
	'..',
	'../../../blenlib',
	'intern/include',
	'#/intern/guardedalloc',
	'../../../makesdna']

defs = []
                 
env.BlenderLib ('bf_cineon', source_files, incs, defs, libtype=['core','player'], priority = [90, 200])
